#!/usr/bin/env python3
#
# loadusr -W ./rio_precompile
#

import os
import time
import hal

h = hal.component("rio_precompile")
h.newpin("compile", hal.HAL_FLOAT, hal.HAL_IN)

h["compile"] = 1

do_compile = False

if not os.path.isfile("/usr/lib/linuxcnc/modules/rio.so"):
    do_compile = True
else:
    mtime_c = os.stat("rio.c").st_mtime
    mtime_so = os.stat("/usr/lib/linuxcnc/modules/rio.so").st_mtime
    if mtime_c > mtime_so:
        do_compile = True

if do_compile:
    os.system("halcompile --install rio.c")

h["compile"] = 0
h.ready()


while True:
    time.sleep(0.5)
