// Generated by rio-generator

#include <time.h>
#include <unistd.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <sys/mman.h>
#include <errno.h>
#include <fcntl.h>
#include <termios.h>

#include <rio.h>

#define MODNAME "riocomp-fpga0"
#define PREFIX "fpga0"
#define JOINTS 3
#define BUFFER_SIZE_RX 40
#define BUFFER_SIZE_TX 40
#define OSC_CLOCK 27000000
#define UDP_IP "192.168.11.194"
#define SRC_PORT 2391
#define DST_PORT 2390
#define SERIAL_PORT "/dev/ttyUSB1"
#define SERIAL_BAUD B1000000
#define SPI_PIN_MOSI 10
#define SPI_PIN_MISO 9
#define SPI_PIN_CLK 11
#define SPI_PIN_CS 8
#define SPI_SPEED BCM2835_SPI_CLOCK_DIVIDER_256


struct timespec ns_timestamp;

long rtapi_get_time() {
    clock_gettime(CLOCK_MONOTONIC, &ns_timestamp);
    return (double)ns_timestamp.tv_sec * 1000000000 + ns_timestamp.tv_nsec;
}

void rtapi_delay(int ns) {
    usleep(ns / 1000);
}


static int 			      comp_id;
static const char 	      *modname = MODNAME;
static const char 	      *prefix = PREFIX;

uint32_t pkg_counter = 0;
uint32_t err_total = 0;
uint32_t err_counter = 0;

long stamp_last = 0;
float fpga_stamp_last = 0;
uint32_t fpga_timestamp = 0;

void rio_readwrite(void *inst, long period);
int error_handler(int retval);

static data_t *data;

data_t *register_signals(void) {
    int retval = 0;
    data = (data_t*)malloc(sizeof(data_t));
    memset(&data->VARIN128_MODBUS0_RXDATA, 0, 16);
    memset(&data->VAROUT128_MODBUS0_TXDATA, 0, 16);
    data->VAROUT32_STEPDIR0_VELOCITY = 0;
    data->VARIN32_STEPDIR0_POSITION = 0;
    data->VAROUT32_STEPDIR1_VELOCITY = 0;
    data->VARIN32_STEPDIR1_POSITION = 0;
    data->VAROUT32_STEPDIR2_VELOCITY = 0;
    data->VARIN32_STEPDIR2_POSITION = 0;
    data->VARIN16_I2CBUS0_LM75_0_TEMP = 0;
    data->VARIN1_I2CBUS0_LM75_0_VALID = 0;
    data->VAROUT1_STEPDIR0_ENABLE = 0;
    data->VAROUT1_STEPDIR1_ENABLE = 0;
    data->VAROUT1_STEPDIR2_ENABLE = 0;
    data->VARIN1_BITIN0_BIT = 0;
    data->VARIN1_BITIN1_BIT = 0;
    data->VARIN1_BITIN2_BIT = 0;
    data->VAROUT1_FPGA0_WLED_0_GREEN = 0;
    data->VAROUT1_FPGA0_WLED_0_BLUE = 0;
    data->VAROUT1_FPGA0_WLED_0_RED = 0;
    data->VAROUT1_BITOUT0_BIT = 0;

    data->sys_status = (bool*)malloc(sizeof(bool));
    data->sys_enable = (bool*)malloc(sizeof(bool));
    data->sys_enable_request = (bool*)malloc(sizeof(bool));
    data->machine_on = (bool*)malloc(sizeof(bool));
    data->sys_simulation = (bool*)malloc(sizeof(bool));
    *data->sys_simulation = 0;
    data->duration = (float*)malloc(sizeof(float));
    *data->duration = rtapi_get_time();
    data->SIGIN_FPGA0_MODBUS0_TEMPERATURE_SCALE = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_MODBUS0_TEMPERATURE_SCALE = 1.0;
    data->SIGIN_FPGA0_MODBUS0_TEMPERATURE_OFFSET = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_MODBUS0_TEMPERATURE_OFFSET = 0.0;
    data->SIGIN_FPGA0_MODBUS0_TEMPERATURE = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_MODBUS0_TEMPERATURE = 0;
    data->SIGIN_FPGA0_MODBUS0_TEMPERATURE_ABS = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_MODBUS0_TEMPERATURE_ABS = 0;
    data->SIGIN_FPGA0_MODBUS0_TEMPERATURE_S32 = (int32_t*)malloc(sizeof(int32_t));
    *data->SIGIN_FPGA0_MODBUS0_TEMPERATURE_S32 = 0;
    data->SIGIN_FPGA0_MODBUS0_TEMPERATURE_U32_ABS = (uint32_t*)malloc(sizeof(uint32_t));
    *data->SIGIN_FPGA0_MODBUS0_TEMPERATURE_U32_ABS = 0;
    data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP_SCALE = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP_SCALE = 1.0;
    data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP_OFFSET = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP_OFFSET = 0.0;
    data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP = 0;
    data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP_ABS = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP_ABS = 0;
    data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP_S32 = (int32_t*)malloc(sizeof(int32_t));
    *data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP_S32 = 0;
    data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP_U32_ABS = (uint32_t*)malloc(sizeof(uint32_t));
    *data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP_U32_ABS = 0;
    data->SIGIN_FPGA0_I2CBUS0_LM75_0_VALID = (bool*)malloc(sizeof(bool));
    *data->SIGIN_FPGA0_I2CBUS0_LM75_0_VALID = 0;
    data->SIGIN_FPGA0_I2CBUS0_LM75_0_VALID_not = (bool*)malloc(sizeof(bool));
    *data->SIGIN_FPGA0_I2CBUS0_LM75_0_VALID_not = 1 - *data->SIGIN_FPGA0_I2CBUS0_LM75_0_VALID;
    data->SIGOUT_FPGA0_STEPDIR0_VELOCITY_SCALE = (float*)malloc(sizeof(float));
    *data->SIGOUT_FPGA0_STEPDIR0_VELOCITY_SCALE = 1.0;
    data->SIGOUT_FPGA0_STEPDIR0_VELOCITY_OFFSET = (float*)malloc(sizeof(float));
    *data->SIGOUT_FPGA0_STEPDIR0_VELOCITY_OFFSET = 0.0;
    data->SIGOUT_FPGA0_STEPDIR0_VELOCITY = (float*)malloc(sizeof(float));
    *data->SIGOUT_FPGA0_STEPDIR0_VELOCITY = 0;
    data->SIGIN_FPGA0_STEPDIR0_POSITION_SCALE = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_STEPDIR0_POSITION_SCALE = 1.0;
    data->SIGIN_FPGA0_STEPDIR0_POSITION_OFFSET = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_STEPDIR0_POSITION_OFFSET = 0.0;
    data->SIGIN_FPGA0_STEPDIR0_POSITION = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_STEPDIR0_POSITION = 0;
    data->SIGIN_FPGA0_STEPDIR0_POSITION_ABS = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_STEPDIR0_POSITION_ABS = 0;
    data->SIGIN_FPGA0_STEPDIR0_POSITION_S32 = (int32_t*)malloc(sizeof(int32_t));
    *data->SIGIN_FPGA0_STEPDIR0_POSITION_S32 = 0;
    data->SIGIN_FPGA0_STEPDIR0_POSITION_U32_ABS = (uint32_t*)malloc(sizeof(uint32_t));
    *data->SIGIN_FPGA0_STEPDIR0_POSITION_U32_ABS = 0;
    data->SIGOUT_FPGA0_STEPDIR0_ENABLE = (bool*)malloc(sizeof(bool));
    *data->SIGOUT_FPGA0_STEPDIR0_ENABLE = 0;
    data->SIGOUT_FPGA0_STEPDIR1_VELOCITY_SCALE = (float*)malloc(sizeof(float));
    *data->SIGOUT_FPGA0_STEPDIR1_VELOCITY_SCALE = 1.0;
    data->SIGOUT_FPGA0_STEPDIR1_VELOCITY_OFFSET = (float*)malloc(sizeof(float));
    *data->SIGOUT_FPGA0_STEPDIR1_VELOCITY_OFFSET = 0.0;
    data->SIGOUT_FPGA0_STEPDIR1_VELOCITY = (float*)malloc(sizeof(float));
    *data->SIGOUT_FPGA0_STEPDIR1_VELOCITY = 0;
    data->SIGIN_FPGA0_STEPDIR1_POSITION_SCALE = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_STEPDIR1_POSITION_SCALE = 1.0;
    data->SIGIN_FPGA0_STEPDIR1_POSITION_OFFSET = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_STEPDIR1_POSITION_OFFSET = 0.0;
    data->SIGIN_FPGA0_STEPDIR1_POSITION = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_STEPDIR1_POSITION = 0;
    data->SIGIN_FPGA0_STEPDIR1_POSITION_ABS = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_STEPDIR1_POSITION_ABS = 0;
    data->SIGIN_FPGA0_STEPDIR1_POSITION_S32 = (int32_t*)malloc(sizeof(int32_t));
    *data->SIGIN_FPGA0_STEPDIR1_POSITION_S32 = 0;
    data->SIGIN_FPGA0_STEPDIR1_POSITION_U32_ABS = (uint32_t*)malloc(sizeof(uint32_t));
    *data->SIGIN_FPGA0_STEPDIR1_POSITION_U32_ABS = 0;
    data->SIGOUT_FPGA0_STEPDIR1_ENABLE = (bool*)malloc(sizeof(bool));
    *data->SIGOUT_FPGA0_STEPDIR1_ENABLE = 0;
    data->SIGOUT_FPGA0_STEPDIR2_VELOCITY_SCALE = (float*)malloc(sizeof(float));
    *data->SIGOUT_FPGA0_STEPDIR2_VELOCITY_SCALE = 1.0;
    data->SIGOUT_FPGA0_STEPDIR2_VELOCITY_OFFSET = (float*)malloc(sizeof(float));
    *data->SIGOUT_FPGA0_STEPDIR2_VELOCITY_OFFSET = 0.0;
    data->SIGOUT_FPGA0_STEPDIR2_VELOCITY = (float*)malloc(sizeof(float));
    *data->SIGOUT_FPGA0_STEPDIR2_VELOCITY = 0;
    data->SIGIN_FPGA0_STEPDIR2_POSITION_SCALE = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_STEPDIR2_POSITION_SCALE = 1.0;
    data->SIGIN_FPGA0_STEPDIR2_POSITION_OFFSET = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_STEPDIR2_POSITION_OFFSET = 0.0;
    data->SIGIN_FPGA0_STEPDIR2_POSITION = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_STEPDIR2_POSITION = 0;
    data->SIGIN_FPGA0_STEPDIR2_POSITION_ABS = (float*)malloc(sizeof(float));
    *data->SIGIN_FPGA0_STEPDIR2_POSITION_ABS = 0;
    data->SIGIN_FPGA0_STEPDIR2_POSITION_S32 = (int32_t*)malloc(sizeof(int32_t));
    *data->SIGIN_FPGA0_STEPDIR2_POSITION_S32 = 0;
    data->SIGIN_FPGA0_STEPDIR2_POSITION_U32_ABS = (uint32_t*)malloc(sizeof(uint32_t));
    *data->SIGIN_FPGA0_STEPDIR2_POSITION_U32_ABS = 0;
    data->SIGOUT_FPGA0_STEPDIR2_ENABLE = (bool*)malloc(sizeof(bool));
    *data->SIGOUT_FPGA0_STEPDIR2_ENABLE = 0;
    data->SIGIN_FPGA0_BITIN0_BIT = (bool*)malloc(sizeof(bool));
    *data->SIGIN_FPGA0_BITIN0_BIT = 0;
    data->SIGIN_FPGA0_BITIN0_BIT_not = (bool*)malloc(sizeof(bool));
    *data->SIGIN_FPGA0_BITIN0_BIT_not = 1 - *data->SIGIN_FPGA0_BITIN0_BIT;
    data->SIGIN_FPGA0_BITIN1_BIT = (bool*)malloc(sizeof(bool));
    *data->SIGIN_FPGA0_BITIN1_BIT = 0;
    data->SIGIN_FPGA0_BITIN1_BIT_not = (bool*)malloc(sizeof(bool));
    *data->SIGIN_FPGA0_BITIN1_BIT_not = 1 - *data->SIGIN_FPGA0_BITIN1_BIT;
    data->SIGIN_FPGA0_BITIN2_BIT = (bool*)malloc(sizeof(bool));
    *data->SIGIN_FPGA0_BITIN2_BIT = 0;
    data->SIGIN_FPGA0_BITIN2_BIT_not = (bool*)malloc(sizeof(bool));
    *data->SIGIN_FPGA0_BITIN2_BIT_not = 1 - *data->SIGIN_FPGA0_BITIN2_BIT;
    data->SIGOUT_FPGA0_FPGA0_WLED_0_GREEN = (bool*)malloc(sizeof(bool));
    *data->SIGOUT_FPGA0_FPGA0_WLED_0_GREEN = 0;
    data->SIGOUT_FPGA0_FPGA0_WLED_0_BLUE = (bool*)malloc(sizeof(bool));
    *data->SIGOUT_FPGA0_FPGA0_WLED_0_BLUE = 0;
    data->SIGOUT_FPGA0_FPGA0_WLED_0_RED = (bool*)malloc(sizeof(bool));
    *data->SIGOUT_FPGA0_FPGA0_WLED_0_RED = 0;
    data->SIGOUT_FPGA0_BITOUT0_BIT = (bool*)malloc(sizeof(bool));
    *data->SIGOUT_FPGA0_BITOUT0_BIT = 0;
    return data;
}

/*
    interface: UDP
*/

#include <string.h>
#include <stdio.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>

#define SEND_TIMEOUT_US 10
#define RECV_TIMEOUT_US 10
#define READ_PCK_DELAY_NS 1000
#define READ_PCK_TIMEOUT_MS 2

static int udpSocket;
static int errCount;
struct sockaddr_in dstAddr, srcAddr;
struct hostent *server;

int udp_init(const char *dstAddress, int dstPort, int srcPort) {
    int ret;

    // Create a UDP socket
    udpSocket = socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP);
    if (udpSocket < 0) {
        printf("ERROR: can't open socket: %s\n", "error");
        return -1;
    }

    bzero((char*) &dstAddr, sizeof(dstAddr));
    dstAddr.sin_family = AF_INET;
    dstAddr.sin_addr.s_addr = inet_addr(dstAddress);
    dstAddr.sin_port = htons(dstPort);

    bzero((char*) &srcAddr, sizeof(srcAddr));
    srcAddr.sin_family = AF_INET;
    srcAddr.sin_addr.s_addr = htonl(INADDR_ANY);
    srcAddr.sin_port = htons(srcPort);

    printf("INFO: target is udp port: %s:%i\n", dstAddress, dstPort);
    printf("INFO: listening on udp port: %s:%i\n", "0.0.0.0", srcPort);

    // bind the local socket to SCR_PORT
    ret = bind(udpSocket, (struct sockaddr *) &srcAddr, sizeof(srcAddr));
    if (ret < 0) {
        printf("ERROR: can't bind: %s\n", "error");
        return -1;
    }

    // Connect to send and receive only to the server_addr
    ret = connect(udpSocket, (struct sockaddr*) &dstAddr, sizeof(struct sockaddr_in));
    if (ret < 0) {
        printf("ERROR: can't connect: %s\n", "error");
        return -1;
    }

    struct timeval timeout;
    timeout.tv_sec = 0;
    timeout.tv_usec = RECV_TIMEOUT_US;

    ret = setsockopt(udpSocket, SOL_SOCKET, SO_RCVTIMEO, (char*) &timeout, sizeof(timeout));
    if (ret < 0) {
        printf("ERROR: can't set receive timeout socket option: %s\n", "error");
        return -1;
    }

    timeout.tv_usec = SEND_TIMEOUT_US;
    ret = setsockopt(udpSocket, SOL_SOCKET, SO_SNDTIMEO, (char*) &timeout,
                     sizeof(timeout));
    if (ret < 0) {
        printf("ERROR: can't set send timeout socket option: %s\n", "error");
        return -1;
    }

    return 0;
}

void udp_tx(uint8_t *txBuffer, uint16_t size) {
    // Send datagram
    send(udpSocket, txBuffer, size, 0);
}

int udp_rx(uint8_t *rxBuffer, uint16_t size, uint8_t udp_async) {
    int i;
    int ret;
    long t1;
    long t2;
    uint8_t rxBufferTmp[1024];

    for (i = 0; i < 1024; i++) {
        rxBufferTmp[i] = 0;
    }

    // Receive incoming datagram
    if (udp_async == 1) {
        ret = recv(udpSocket, rxBufferTmp, size * 2, MSG_DONTWAIT);
    } else {
        t1 = rtapi_get_time();
        do {
            ret = recv(udpSocket, rxBufferTmp, size * 2, 0);
            if (ret < 0) {
                rtapi_delay(READ_PCK_DELAY_NS);
            }
            t2 = rtapi_get_time();
        }
        while ((ret < 0) && ((t2 - t1) < READ_PCK_TIMEOUT_MS * 1000 * 1000));
    }

    if (ret > 0) {
        errCount = 0;
        if (ret == size) {
            memcpy(rxBuffer, rxBufferTmp, size);
        } else {
            printf("wrong size = %d\n", ret);
            for (i = 0; i < ret; i++) {
                printf("%d ", rxBufferTmp[i]);
            }
            printf("\n");
        }
        /*
        printf("rx:");
        for (i = 0; i < ret; i++) {
            printf(" %d,", rxBuffer[i]);
        }
        printf("\n");
        */
    } else {
        errCount++;
        // printf("Ethernet TIMEOUT: N = %d (ret: %d)\n", errCount, ret);
    }

    return ret;
}

void udp_exit(void) {
}

int interface_init(int argc, char **argv) {
    char dstAddress[1024];
    int dstPort = DST_PORT;
    if (argc > 1) {
        int ip0 = 0;
        int ip1 = 0;
        int ip2 = 0;
        int ip3 = 0;
        int port = 0;
        int ret = sscanf(argv[1], "%d.%d.%d.%d:%d", &ip0, &ip1, &ip2, &ip3, &port);
        if (ret >= 4) {
            sprintf(dstAddress, "%d.%d.%d.%d", ip0, ip1, ip2, ip3);
            if (ret == 5) {
                dstPort = port;
            }
        }
        udp_init(dstAddress, dstPort, SRC_PORT);
    } else {
        udp_init(UDP_IP, DST_PORT, SRC_PORT);
    }
    return 0;
}

data_t *init(int argc, char **argv) {
    data = register_signals();
    interface_init(argc, argv);
    return data;
}

void interface_exit(void) {
    udp_exit();
}


/*
    hal functions
*/

/***********************************************************************
*                       HELPER FUNCTIONS                               *
************************************************************************/

uint16_t crc16_update(uint16_t crc, uint8_t a) {
	int i;

	crc ^= (uint16_t)a;
	for (i = 0; i < 8; ++i) {
		if (crc & 1)
			crc = (crc >> 1) ^ 0xA001;
		else
			crc = (crc >> 1);
	}

	return crc;
}


/***********************************************************************/


/***********************************************************************
*                         PLUGIN GLOBALS                               *
************************************************************************/

long modbus0_last_rx = 0;
uint8_t modbus0_signal_active = 0;
uint8_t modbus0_signal_next = 0;













/***********************************************************************/

// Generated by component_signal_converter()
// output: SIGOUT -> calc -> VAROUT -> txBuffer
void convert_frame_modbus0_output(data_t *data) {
    static float timeout = 200.0;
    static float delay = 0;
    static long frame_stamp_last = 0;
    static uint8_t frame_id = 0;
    static uint8_t frame_io[16] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    static uint8_t frame_data[16] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    float frame_time = 0.0;
    uint8_t frame_id_last = 0;
    uint8_t frame_id_ack = 0;
    uint8_t frame_timeout = 0;
    uint8_t frame_ack = 0;
    uint8_t frame_len = 0;

    frame_time = (float)(stamp_last - frame_stamp_last) / 1000000.0;
    if (timeout > 0 && frame_time > timeout) {
        // rtapi_print("timeout: %f\n", frame_time);
        frame_timeout = 1;
    }

    frame_id_ack = data->VARIN128_MODBUS0_RXDATA[0];
    if (frame_id_ack == frame_id) {
        frame_ack = 1;
    }

    if (timeout == 0 || frame_timeout == 1 || (frame_ack == 1 && (float)(stamp_last - modbus0_last_rx) / 1000000.0 > delay)) {
        frame_id_last = frame_id;
        frame_id += 1;

        /*** get plugin vars ***/

        float value_temperature = *data->SIGIN_FPGA0_MODBUS0_TEMPERATURE;

        /***********************/

        /*** plugin code ***/

        if (frame_timeout == 1) {
            // rtapi_print("rx error: timeout: %d\n", modbus0_signal_active);
        }

        // check for changes on prio values
        {
            if (modbus0_signal_next < -1) {
                modbus0_signal_next++;
            } else {
                modbus0_signal_next = 0;
            }
            modbus0_signal_active = modbus0_signal_next;
        }

        switch (modbus0_signal_active) {
        }


        if (frame_len == 0) {
            delay = 0;
            timeout = 0;
        } else {
            uint8_t i = 0;
            uint16_t crc = 0xFFFF;
            for (i = 0; i < frame_len; i++) {
                crc = crc16_update(crc, frame_data[i]);
            }
            frame_data[frame_len] = crc & 0xFF;
            frame_data[frame_len + 1] = crc>>8 & 0xFF;
            frame_len += 2;
        }

        /*******************/

        /*** update plugin vars ***/

        *data->SIGIN_FPGA0_MODBUS0_TEMPERATURE = value_temperature;

        /**************************/

        if (frame_len > 0) {
            frame_io[0] = frame_id;
            frame_io[1] = frame_len;
            frame_stamp_last = stamp_last;
            memcpy(&frame_io[2], &frame_data, 14);
        }
    }

    memcpy(&data->VAROUT128_MODBUS0_TXDATA, &frame_io, 16);
}

void convert_varout32_stepdir0_velocity(data_t *data){
    float value = *data->SIGOUT_FPGA0_STEPDIR0_VELOCITY;
    value = value * *data->SIGOUT_FPGA0_STEPDIR0_VELOCITY_SCALE;
    value = value + *data->SIGOUT_FPGA0_STEPDIR0_VELOCITY_OFFSET;
    if (value != 0) {
                value = OSC_CLOCK / value / 2;
            }
    data->VAROUT32_STEPDIR0_VELOCITY = value;
}

void convert_varout1_stepdir0_enable(data_t *data){
    bool value = *data->SIGOUT_FPGA0_STEPDIR0_ENABLE;
    
    data->VAROUT1_STEPDIR0_ENABLE = value;
}

void convert_varout32_stepdir1_velocity(data_t *data){
    float value = *data->SIGOUT_FPGA0_STEPDIR1_VELOCITY;
    value = value * *data->SIGOUT_FPGA0_STEPDIR1_VELOCITY_SCALE;
    value = value + *data->SIGOUT_FPGA0_STEPDIR1_VELOCITY_OFFSET;
    if (value != 0) {
                value = OSC_CLOCK / value / 2;
            }
    data->VAROUT32_STEPDIR1_VELOCITY = value;
}

void convert_varout1_stepdir1_enable(data_t *data){
    bool value = *data->SIGOUT_FPGA0_STEPDIR1_ENABLE;
    
    data->VAROUT1_STEPDIR1_ENABLE = value;
}

void convert_varout32_stepdir2_velocity(data_t *data){
    float value = *data->SIGOUT_FPGA0_STEPDIR2_VELOCITY;
    value = value * *data->SIGOUT_FPGA0_STEPDIR2_VELOCITY_SCALE;
    value = value + *data->SIGOUT_FPGA0_STEPDIR2_VELOCITY_OFFSET;
    if (value != 0) {
                value = OSC_CLOCK / value / 2;
            }
    data->VAROUT32_STEPDIR2_VELOCITY = value;
}

void convert_varout1_stepdir2_enable(data_t *data){
    bool value = *data->SIGOUT_FPGA0_STEPDIR2_ENABLE;
    
    data->VAROUT1_STEPDIR2_ENABLE = value;
}

void convert_varout1_fpga0_wled_0_green(data_t *data){
    bool value = *data->SIGOUT_FPGA0_FPGA0_WLED_0_GREEN;
    
    data->VAROUT1_FPGA0_WLED_0_GREEN = value;
}

void convert_varout1_fpga0_wled_0_blue(data_t *data){
    bool value = *data->SIGOUT_FPGA0_FPGA0_WLED_0_BLUE;
    
    data->VAROUT1_FPGA0_WLED_0_BLUE = value;
}

void convert_varout1_fpga0_wled_0_red(data_t *data){
    bool value = *data->SIGOUT_FPGA0_FPGA0_WLED_0_RED;
    
    data->VAROUT1_FPGA0_WLED_0_RED = value;
}

void convert_varout1_bitout0_bit(data_t *data){
    bool value = *data->SIGOUT_FPGA0_BITOUT0_BIT;
    
    data->VAROUT1_BITOUT0_BIT = value;
}


// input: rxBuffer -> VAROUT -> calc -> SIGOUT
void convert_frame_modbus0_input(data_t *data) {
    static uint8_t frame_id_last = 0;
    uint8_t frame_data[16] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    uint8_t cn = 0;
    uint8_t frame_new = 0;
    uint8_t frame_id = 0;
    uint8_t frame_len = 0;
    frame_id = data->VARIN128_MODBUS0_RXDATA[1];
    frame_len = data->VARIN128_MODBUS0_RXDATA[2];
    if (frame_id_last != frame_id) {
        frame_id_last = frame_id;
        frame_new = 1;
        modbus0_last_rx = stamp_last;
    }
    for (cn = 0; cn < frame_len; cn++) {
        frame_data[cn] = data->VARIN128_MODBUS0_RXDATA[frame_len - cn + 2];
    }

    /*** get plugin vars ***/

    float value_temperature = *data->SIGIN_FPGA0_MODBUS0_TEMPERATURE;

    /***********************/

    /*** plugin code ***/

    if (frame_new == 1) {
        uint8_t n = 0;
        uint8_t data_len = 0;
        uint8_t data_addr = frame_data[0];
        uint8_t data_type = frame_data[1];
        uint16_t crc = 0xFFFF;
        for (n = 0; n < frame_len - 2; n++) {
           crc = crc16_update(crc, frame_data[n]);
        }
        if ((crc & 0xFF) == frame_data[frame_len - 2] && (crc>>8 & 0xFF) == frame_data[frame_len - 1]) {
            switch (modbus0_signal_active) {
            }
        } else {
            // rtapi_print("ERROR: CSUM: %d|%d != %d|%d\n", crc & 0xFF, crc>>8 & 0xFF, frame_data[frame_len - 2], frame_data[frame_len - 1]);
        }
        // rtapi_print("rx frame %i %i: ", frame_id, frame_len);
        // for (n = 0; n < frame_len; n++) {
        //     rtapi_print("%i, ", frame_data[n]);
        // }
        // rtapi_print("\n");
    }

    /*******************/

    /*** update plugin vars ***/

    *data->SIGIN_FPGA0_MODBUS0_TEMPERATURE = value_temperature;
    *data->SIGIN_FPGA0_MODBUS0_TEMPERATURE_S32 = (int)value_temperature;

    /**************************/
}

void convert_sigin_fpga0_i2cbus0_lm75_0_temp(data_t *data) {
    float value = data->VARIN16_I2CBUS0_LM75_0_TEMP;
    float offset = *data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP_OFFSET;
    float scale = *data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP_SCALE;
    float last_value = *data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP;
    static float last_raw_value = 0.0;
    float raw_value = value;
    // -- calc --
    value = value / 256.0;
    // ----------
    value = value + offset;
    value = value / scale;
    *data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP_ABS = abs(value);
    *data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP_S32 = value;
    *data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP_U32_ABS = abs(value);
    *data->SIGIN_FPGA0_I2CBUS0_LM75_0_TEMP = value;

    last_raw_value = raw_value;
}

void convert_sigin_fpga0_i2cbus0_lm75_0_valid(data_t *data) {
    bool value = data->VARIN1_I2CBUS0_LM75_0_VALID;
    *data->SIGIN_FPGA0_I2CBUS0_LM75_0_VALID = value;
    *data->SIGIN_FPGA0_I2CBUS0_LM75_0_VALID_not = 1 - value;
}

void convert_sigin_fpga0_stepdir0_position(data_t *data) {
    float value = data->VARIN32_STEPDIR0_POSITION;
    float offset = *data->SIGIN_FPGA0_STEPDIR0_POSITION_OFFSET;
    float scale = *data->SIGIN_FPGA0_STEPDIR0_POSITION_SCALE;
    float last_value = *data->SIGIN_FPGA0_STEPDIR0_POSITION;
    static float last_raw_value = 0.0;
    float raw_value = value;
    value = value + offset;
    value = value / scale;
    if (*data->sys_simulation == 1) {
        value = *data->SIGIN_FPGA0_STEPDIR0_POSITION + *data->SIGOUT_FPGA0_STEPDIR0_VELOCITY / 1000.0;
    }
    *data->SIGIN_FPGA0_STEPDIR0_POSITION_ABS = abs(value);
    *data->SIGIN_FPGA0_STEPDIR0_POSITION_S32 = value;
    *data->SIGIN_FPGA0_STEPDIR0_POSITION_U32_ABS = abs(value);
    *data->SIGIN_FPGA0_STEPDIR0_POSITION = value;

    last_raw_value = raw_value;
}

void convert_sigin_fpga0_stepdir1_position(data_t *data) {
    float value = data->VARIN32_STEPDIR1_POSITION;
    float offset = *data->SIGIN_FPGA0_STEPDIR1_POSITION_OFFSET;
    float scale = *data->SIGIN_FPGA0_STEPDIR1_POSITION_SCALE;
    float last_value = *data->SIGIN_FPGA0_STEPDIR1_POSITION;
    static float last_raw_value = 0.0;
    float raw_value = value;
    value = value + offset;
    value = value / scale;
    if (*data->sys_simulation == 1) {
        value = *data->SIGIN_FPGA0_STEPDIR1_POSITION + *data->SIGOUT_FPGA0_STEPDIR1_VELOCITY / 1000.0;
    }
    *data->SIGIN_FPGA0_STEPDIR1_POSITION_ABS = abs(value);
    *data->SIGIN_FPGA0_STEPDIR1_POSITION_S32 = value;
    *data->SIGIN_FPGA0_STEPDIR1_POSITION_U32_ABS = abs(value);
    *data->SIGIN_FPGA0_STEPDIR1_POSITION = value;

    last_raw_value = raw_value;
}

void convert_sigin_fpga0_stepdir2_position(data_t *data) {
    float value = data->VARIN32_STEPDIR2_POSITION;
    float offset = *data->SIGIN_FPGA0_STEPDIR2_POSITION_OFFSET;
    float scale = *data->SIGIN_FPGA0_STEPDIR2_POSITION_SCALE;
    float last_value = *data->SIGIN_FPGA0_STEPDIR2_POSITION;
    static float last_raw_value = 0.0;
    float raw_value = value;
    value = value + offset;
    value = value / scale;
    if (*data->sys_simulation == 1) {
        value = *data->SIGIN_FPGA0_STEPDIR2_POSITION + *data->SIGOUT_FPGA0_STEPDIR2_VELOCITY / 1000.0;
    }
    *data->SIGIN_FPGA0_STEPDIR2_POSITION_ABS = abs(value);
    *data->SIGIN_FPGA0_STEPDIR2_POSITION_S32 = value;
    *data->SIGIN_FPGA0_STEPDIR2_POSITION_U32_ABS = abs(value);
    *data->SIGIN_FPGA0_STEPDIR2_POSITION = value;

    last_raw_value = raw_value;
}

void convert_sigin_fpga0_bitin0_bit(data_t *data) {
    bool value = data->VARIN1_BITIN0_BIT;
    *data->SIGIN_FPGA0_BITIN0_BIT = value;
    *data->SIGIN_FPGA0_BITIN0_BIT_not = 1 - value;
}

void convert_sigin_fpga0_bitin1_bit(data_t *data) {
    bool value = data->VARIN1_BITIN1_BIT;
    *data->SIGIN_FPGA0_BITIN1_BIT = value;
    *data->SIGIN_FPGA0_BITIN1_BIT_not = 1 - value;
}

void convert_sigin_fpga0_bitin2_bit(data_t *data) {
    bool value = data->VARIN1_BITIN2_BIT;
    *data->SIGIN_FPGA0_BITIN2_BIT = value;
    *data->SIGIN_FPGA0_BITIN2_BIT_not = 1 - value;
}



// Generated by component_buffer_converter()
void convert_outputs(void) {
    // output loop: SIGOUT -> calc -> VAROUT -> txBuffer
    convert_frame_modbus0_output(data);
    convert_varout32_stepdir0_velocity(data);
    convert_varout1_stepdir0_enable(data);
    convert_varout32_stepdir1_velocity(data);
    convert_varout1_stepdir1_enable(data);
    convert_varout32_stepdir2_velocity(data);
    convert_varout1_stepdir2_enable(data);
    convert_varout1_fpga0_wled_0_green(data);
    convert_varout1_fpga0_wled_0_blue(data);
    convert_varout1_fpga0_wled_0_red(data);
    convert_varout1_bitout0_bit(data);
}

void convert_inputs(void) {
    // input: rxBuffer -> VAROUT -> calc -> SIGOUT
    convert_frame_modbus0_input(data);
    convert_sigin_fpga0_i2cbus0_lm75_0_temp(data);
    convert_sigin_fpga0_i2cbus0_lm75_0_valid(data);
    convert_sigin_fpga0_stepdir0_position(data);
    convert_sigin_fpga0_stepdir1_position(data);
    convert_sigin_fpga0_stepdir2_position(data);
    convert_sigin_fpga0_bitin0_bit(data);
    convert_sigin_fpga0_bitin1_bit(data);
    convert_sigin_fpga0_bitin2_bit(data);
}

// Generated by component_buffer()
void write_txbuffer(uint8_t *txBuffer) {
    // PC -> FPGA (263 + 57)
    int i = 0;
    for (i = 0; i < BUFFER_SIZE_TX; i++) {
        txBuffer[i] = 0;
    }
    // raw vars to txBuffer
    txBuffer[0] = 0x74; // 320
    txBuffer[1] = 0x69; // 312
    txBuffer[2] = 0x72; // 304
    txBuffer[3] = 0x77; // 296
    memcpy(&txBuffer[4], &data->VAROUT128_MODBUS0_TXDATA, 16); // 288
    memcpy(&txBuffer[20], &data->VAROUT32_STEPDIR0_VELOCITY, 4); // 160
    memcpy(&txBuffer[24], &data->VAROUT32_STEPDIR1_VELOCITY, 4); // 128
    memcpy(&txBuffer[28], &data->VAROUT32_STEPDIR2_VELOCITY, 4); // 96
    txBuffer[32] |= (data->VAROUT1_STEPDIR0_ENABLE<<7); // 64
    txBuffer[32] |= (data->VAROUT1_STEPDIR1_ENABLE<<6); // 63
    txBuffer[32] |= (data->VAROUT1_STEPDIR2_ENABLE<<5); // 62
    txBuffer[32] |= (data->VAROUT1_FPGA0_WLED_0_GREEN<<4); // 61
    txBuffer[32] |= (data->VAROUT1_FPGA0_WLED_0_BLUE<<3); // 60
    txBuffer[32] |= (data->VAROUT1_FPGA0_WLED_0_RED<<2); // 59
    txBuffer[32] |= (data->VAROUT1_BITOUT0_BIT<<1); // 58
    // FILL: 57
}

void read_rxbuffer(uint8_t *rxBuffer) {
    // FPGA -> PC (315 + 5)
    // memcpy(&header, &rxBuffer[0], 4) // 320;
    memcpy(&fpga_timestamp, &rxBuffer[4], 4); // 288
    memcpy(&data->MULTIPLEXER_INPUT_VALUE, &rxBuffer[8], 2);
    memcpy(&data->MULTIPLEXER_INPUT_ID, &rxBuffer[10], 1);
    memcpy(&data->VARIN128_MODBUS0_RXDATA, &rxBuffer[11], 16); // 232
    memcpy(&data->VARIN32_STEPDIR0_POSITION, &rxBuffer[27], 4); // 104
    memcpy(&data->VARIN32_STEPDIR1_POSITION, &rxBuffer[31], 4); // 72
    memcpy(&data->VARIN32_STEPDIR2_POSITION, &rxBuffer[35], 4); // 40
    data->VARIN1_BITIN0_BIT = (rxBuffer[39] & (1<<7)); // 8
    data->VARIN1_BITIN1_BIT = (rxBuffer[39] & (1<<6)); // 7
    data->VARIN1_BITIN2_BIT = (rxBuffer[39] & (1<<5)); // 6
    // FILL: 5
    if (data->MULTIPLEXER_INPUT_ID == 0) {;
        memcpy(&data->VARIN16_I2CBUS0_LM75_0_TEMP, &data->MULTIPLEXER_INPUT_VALUE, 2);
    };
    if (data->MULTIPLEXER_INPUT_ID == 1) {;
        memcpy(&data->VARIN1_I2CBUS0_LM75_0_VALID, &data->MULTIPLEXER_INPUT_VALUE, 1);
    };
}

void rio_readwrite(void *inst, long period) {
    int ret = 0;
    uint8_t i = 0;
    uint8_t rxBuffer[BUFFER_SIZE_RX * 2];
    uint8_t txBuffer[BUFFER_SIZE_TX * 2];
    if (*data->sys_enable_request == 1) {
        *data->sys_status = 1;
    }
    long stamp_new = rtapi_get_time();
    float duration2 = (stamp_new - stamp_last) / 1000.0;
    stamp_last = stamp_new;
    float timestamp = (float)fpga_timestamp / (float)OSC_CLOCK;
    *data->duration = timestamp - fpga_stamp_last;
    fpga_stamp_last = timestamp;
    if (1) {
        pkg_counter += 1;
        convert_outputs();
        if (*data->sys_simulation != 1) {
            write_txbuffer(txBuffer);
#ifdef UDP_ASYNC
            ret = udp_rx(rxBuffer, BUFFER_SIZE_RX, 1);
            udp_tx(txBuffer, BUFFER_SIZE_TX);
#else
            udp_tx(txBuffer, BUFFER_SIZE_TX);
            ret = udp_rx(rxBuffer, BUFFER_SIZE_RX, 0);
#endif
            if (ret == BUFFER_SIZE_RX && rxBuffer[0] == 97 && rxBuffer[1] == 116 && rxBuffer[2] == 97 && rxBuffer[3] == 100) {
                if (err_counter > 0) {
                    err_counter = 0;
                    printf("recovered..\n");
                }
                read_rxbuffer(rxBuffer);
                convert_inputs();
            } else {
                err_counter += 1;
                err_total += 1;
                if (ret != BUFFER_SIZE_RX) {
                    printf("%i: wrong data size (len %i/%i err %i/3) - (%i %i - %0.4f %%)", stamp_new, ret, BUFFER_SIZE_RX, err_counter, err_total, pkg_counter, (float)err_total * 100.0 / (float)pkg_counter);
                } else {
                    printf("%i: wrong header (%i/3) - (%i %i - %0.4f %%):", stamp_new, err_counter, err_total, pkg_counter, (float)err_total * 100.0 / (float)pkg_counter);
                }
                for (i = 0; i < ret; i++) {
                    printf("%d ", rxBuffer[i]);
                }
                printf("\n");
                if (err_counter > 3) {
                    printf("too many errors..\n");
                    *data->sys_status = 0;
                }
            }
        } else {
            convert_inputs();
        }
    } else {
        *data->sys_status = 0;
    }
}

