from riocore.plugins import PluginBase


class Plugin(PluginBase):
    def setup(self):
        self.NAME = "encoder"
        self.COMPONENT = "encoder"
        self.INFO = "software counting of quadrature encoder signals"
        self.DESCRIPTION = """encoder is used to measure position by counting the pulses generated by a quadrature encoder.
As a software-based implementation it is much less expensive than hardware,
but has a limited maximum count rate.
The limit is in the range of 10 kHz to 50 kHz, depending on the computer speed and other factors.
If better performance is needed, a hardware encoder counter is a better choice.
Some hardware-based systems can count at MHz rates."""
        self.KEYWORDS = "encoder quadencoder scale jog"
        self.TYPE = "io"
        self.PLUGIN_TYPE = "gpio"
        self.ORIGIN = ""
        self.OPTIONS = {
            "counter-mode": {
                "default": False,
                "type": bool,
                "unit": "",
                "description": "counter-mode",
            },
            "x4-mode": {
                "default": False,
                "type": bool,
                "unit": "",
                "description": "x4-mode",
            },
            "missing-teeth": {
                "default": 0,
                "type": int,
                "min": 0,
                "max": 10,
                "unit": "",
                "description": "missing-teeth",
            },
            "position-scale": {
                "default": 1.0,
                "type": float,
                "min": -10000.0,
                "max": 10000.0,
                "unit": "",
                "description": "scale",
            },
        }

        self.SIGNALS = {
            "position": {
                "direction": "input",
                "description": "position feedback in steps",
            },
            "velocity": {
                "direction": "input",
                "source": "position",
                "description": "calculates revolutions per second",
            },
            "velocity-rpm": {
                "direction": "input",
                "source": "position",
                "description": "calculates revolutions per minute",
            },
        }
        self.PINDEFAULTS = {
            "phase-A": {"direction": "input"},
            "phase-B": {"direction": "input"},
            "phase-Z": {"direction": "input"},
        }

    def update_prefixes(cls, instances):
        for num, instance in enumerate(instances):
            instance.PREFIX = f"encoder.{num}"

    def hal(self, generator):
        for option in ("counter-mode", "x4-mode", "missing-teeth", "position-scale"):
            value = self.plugin_setup.get(option, self.option_default(option))
            if self.OPTIONS[option]["type"] is bool:
                value = 1 if value else 0
            generator.halg.setp_add(f"{self.PREFIX}.{option}", f"{value}")

    def loader(cls, instances):
        output = []
        output.append(f"# encoder component for {len(instances)} inputs(s)")
        output.append(f"loadrt encoder num_chan={len(instances)}")
        output.append("addf encoder.update-counters base-thread")
        output.append("addf encoder.capture-position servo-thread")
        output.append("")
        return "\n".join(output)
