from riocore.plugins import PluginBase


class Plugin(PluginBase):
    def setup(self):
        self.NAME = "encoder"
        self.INFO = "software counting of quadrature encoder signals"
        self.DESCRIPTION = """encoder is used to measure position by counting the pulses generated by a quadrature encoder.
As a software-based implementation it is much less expensive than hardware,
but has a limited maximum count rate.
The limit is in the range of 10 kHz to 50 kHz, depending on the computer speed and other factors.
If better performance is needed, a hardware encoder counter is a better choice.
Some hardware-based systems can count at MHz rates."""
        self.KEYWORDS = "encoder quadencoder scale jog"
        self.TYPE = "io"
        self.IMAGES = ["encoder", "encoder_optical"]
        self.NEEDS = ["gpio", "basethread"]
        self.ORIGIN = ""
        self.OPTIONS = {
            "counter-mode": {
                "default": False,
                "type": bool,
                "unit": "",
                "description": "counter-mode",
            },
            "x4-mode": {
                "default": False,
                "type": bool,
                "unit": "",
                "description": "x4-mode",
            },
            "missing-teeth": {
                "default": 0,
                "type": int,
                "min": 0,
                "max": 10,
                "unit": "",
                "description": "missing-teeth",
            },
            "position-scale": {
                "default": 1.0,
                "type": float,
                "min": -10000.0,
                "max": 10000.0,
                "unit": "",
                "description": "scale",
            },
        }

        self.SIGNALS = {
            "position": {
                "direction": "input",
                "description": "position feedback in steps",
            },
            "velocity": {
                "direction": "input",
                "source": "position",
                "description": "calculates revolutions per second",
            },
            "velocity-rpm": {
                "direction": "input",
                "source": "position",
                "description": "calculates revolutions per minute",
            },
        }
        self.PINDEFAULTS = {
            "phase-A": {
                "direction": "input",
                "type": ["GPIO"],
            },
            "phase-B": {
                "direction": "input",
                "type": ["GPIO"],
            },
            "phase-Z": {
                "direction": "input",
                "optional": True,
                "type": ["GPIO"],
            },
        }
        self.INTERFACE = {
            "position": {
                "size": 32,
                "direction": "input",
            },
        }

    def hal(self, generator):
        if "mcu" in self.MASTER_PROVIDES:
            return
        for option in ("counter-mode", "x4-mode", "missing-teeth", "position-scale"):
            value = self.plugin_setup.get(option, self.option_default(option))
            if self.OPTIONS[option]["type"] is bool:
                value = 1 if value else 0
            generator.halg.setp_add(f"{self.PREFIX}.{option}", f"{value}")

    @classmethod
    def component_loader(cls, instances):
        inum = 0
        for instance in instances:
            if "mcu" not in instance.MASTER_PROVIDES:
                inum += 1
        if not inum:
            return ""
        output = []
        output.append(f"# encoder component for {inum} inputs(s)")
        output.append(f"loadrt encoder num_chan={inum}")
        output.append("addf encoder.update-counters base-thread")
        output.append("addf encoder.capture-position servo-thread")
        output.append("")
        return "\n".join(output)
