
FROM debian:12

RUN apt-get update
RUN apt-get -y install python3 python3-pip python3-yaml python3-graphviz python3-pyqtgraph python3-pyqt5 python3-pyqt5.qtsvg python3-lxml 

# for package building
RUN apt-get -y install python3-stdeb dh-python

CMD ["/bin/bash"]

