
FROM debian:11

RUN apt-get update
RUN apt-get -y install wget tar

RUN (cd /opt/ && wget https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2024-09-03/oss-cad-suite-linux-x64-20240903.tgz && tar xzvpf oss-cad-suite-linux-x64-20240903.tgz)

CMD ["/bin/bash"]

