// Generated by rio-generator
#include <ros/ros.h>
#include <std_msgs/String.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Bool.h>
#include <time.h>
#include <sstream>
#include <unistd.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <sys/mman.h>
#include <errno.h>
#include <fcntl.h>
#include <termios.h>

#define MODNAME "riocomp-board0"
#define PREFIX "board0"
#define JOINTS 3
#define BUFFER_SIZE 20
#define OSC_CLOCK 27000000
#define UDP_IP "192.168.11.194"
#define SRC_PORT 2391
#define DST_PORT 2390
#define SERIAL_PORT "/dev/ttyUSB1"
#define SERIAL_BAUD B1000000
#define SPI_PIN_MOSI 10
#define SPI_PIN_MISO 9
#define SPI_PIN_CLK 11
#define SPI_PIN_CS 8
#define SPI_SPEED BCM2835_SPI_CLOCK_DIVIDER_256


struct timespec ns_timestamp;

long rtapi_get_time() {
    clock_gettime(CLOCK_MONOTONIC, &ns_timestamp);
    return (double)ns_timestamp.tv_sec * 1000000000 + ns_timestamp.tv_nsec;
}

void rtapi_delay(int ns) {
    usleep(ns / 1000);
}


static int 			      comp_id;
static const char 	      *modname = MODNAME;
static const char 	      *prefix = PREFIX;

uint32_t pkg_counter = 0;
uint32_t err_total = 0;
uint32_t err_counter = 0;

long stamp_last = 0;
float fpga_stamp_last = 0;
uint32_t fpga_timestamp = 0;

void rio_readwrite(void *inst, long period);
int error_handler(int retval);

typedef struct {
    // hal variables
    bool   *sys_enable;
    bool   *sys_enable_request;
    bool   *sys_status;
    bool   *machine_on;
    bool   *sys_simulation;
    uint32_t   *fpga_timestamp;
    float *duration;
    bool   *SIGOUT_BOARD0_BOARD0_WLED_0_GREEN;
    bool   *SIGOUT_BOARD0_BOARD0_WLED_0_BLUE;
    bool   *SIGOUT_BOARD0_BOARD0_WLED_0_RED;
    float *SIGOUT_BOARD0_STEPDIR0_VELOCITY;
    float *SIGOUT_BOARD0_STEPDIR0_VELOCITY_SCALE;
    float *SIGOUT_BOARD0_STEPDIR0_VELOCITY_OFFSET;
    float *SIGIN_BOARD0_STEPDIR0_POSITION;
    float *SIGIN_BOARD0_STEPDIR0_POSITION_ABS;
    int32_t *SIGIN_BOARD0_STEPDIR0_POSITION_S32;
    uint32_t *SIGIN_BOARD0_STEPDIR0_POSITION_U32_ABS;
    float *SIGIN_BOARD0_STEPDIR0_POSITION_SCALE;
    float *SIGIN_BOARD0_STEPDIR0_POSITION_OFFSET;
    bool   *SIGOUT_BOARD0_STEPDIR0_ENABLE;
    float *SIGOUT_BOARD0_STEPDIR1_VELOCITY;
    float *SIGOUT_BOARD0_STEPDIR1_VELOCITY_SCALE;
    float *SIGOUT_BOARD0_STEPDIR1_VELOCITY_OFFSET;
    float *SIGIN_BOARD0_STEPDIR1_POSITION;
    float *SIGIN_BOARD0_STEPDIR1_POSITION_ABS;
    int32_t *SIGIN_BOARD0_STEPDIR1_POSITION_S32;
    uint32_t *SIGIN_BOARD0_STEPDIR1_POSITION_U32_ABS;
    float *SIGIN_BOARD0_STEPDIR1_POSITION_SCALE;
    float *SIGIN_BOARD0_STEPDIR1_POSITION_OFFSET;
    bool   *SIGOUT_BOARD0_STEPDIR1_ENABLE;
    float *SIGOUT_BOARD0_STEPDIR2_VELOCITY;
    float *SIGOUT_BOARD0_STEPDIR2_VELOCITY_SCALE;
    float *SIGOUT_BOARD0_STEPDIR2_VELOCITY_OFFSET;
    float *SIGIN_BOARD0_STEPDIR2_POSITION;
    float *SIGIN_BOARD0_STEPDIR2_POSITION_ABS;
    int32_t *SIGIN_BOARD0_STEPDIR2_POSITION_S32;
    uint32_t *SIGIN_BOARD0_STEPDIR2_POSITION_U32_ABS;
    float *SIGIN_BOARD0_STEPDIR2_POSITION_SCALE;
    float *SIGIN_BOARD0_STEPDIR2_POSITION_OFFSET;
    bool   *SIGOUT_BOARD0_STEPDIR2_ENABLE;
    // raw variables
    int32_t VAROUT32_STEPDIR0_VELOCITY;
    int32_t VARIN32_STEPDIR0_POSITION;
    int32_t VAROUT32_STEPDIR1_VELOCITY;
    int32_t VARIN32_STEPDIR1_POSITION;
    int32_t VAROUT32_STEPDIR2_VELOCITY;
    int32_t VARIN32_STEPDIR2_POSITION;
    bool VAROUT1_BOARD0_WLED_0_GREEN;
    bool VAROUT1_BOARD0_WLED_0_BLUE;
    bool VAROUT1_BOARD0_WLED_0_RED;
    bool VAROUT1_STEPDIR0_ENABLE;
    bool VAROUT1_STEPDIR1_ENABLE;
    bool VAROUT1_STEPDIR2_ENABLE;

} data_t;
static data_t *data;

void register_signals(void) {
    int retval = 0;
    data->VAROUT32_STEPDIR0_VELOCITY = 0;
    data->VARIN32_STEPDIR0_POSITION = 0;
    data->VAROUT32_STEPDIR1_VELOCITY = 0;
    data->VARIN32_STEPDIR1_POSITION = 0;
    data->VAROUT32_STEPDIR2_VELOCITY = 0;
    data->VARIN32_STEPDIR2_POSITION = 0;
    data->VAROUT1_BOARD0_WLED_0_GREEN = 0;
    data->VAROUT1_BOARD0_WLED_0_BLUE = 0;
    data->VAROUT1_BOARD0_WLED_0_RED = 0;
    data->VAROUT1_STEPDIR0_ENABLE = 0;
    data->VAROUT1_STEPDIR1_ENABLE = 0;
    data->VAROUT1_STEPDIR2_ENABLE = 0;

    data->sys_status = (bool*)malloc(sizeof(bool));
    data->sys_enable = (bool*)malloc(sizeof(bool));
    data->sys_enable_request = (bool*)malloc(sizeof(bool));
    data->machine_on = (bool*)malloc(sizeof(bool));
    data->sys_simulation = (bool*)malloc(sizeof(bool));
    data->duration = (float*)malloc(sizeof(float));
    *data->duration = rtapi_get_time();
    data->SIGOUT_BOARD0_BOARD0_WLED_0_GREEN = (bool*)malloc(sizeof(bool));
    *data->SIGOUT_BOARD0_BOARD0_WLED_0_GREEN = 0;
    data->SIGOUT_BOARD0_BOARD0_WLED_0_BLUE = (bool*)malloc(sizeof(bool));
    *data->SIGOUT_BOARD0_BOARD0_WLED_0_BLUE = 0;
    data->SIGOUT_BOARD0_BOARD0_WLED_0_RED = (bool*)malloc(sizeof(bool));
    *data->SIGOUT_BOARD0_BOARD0_WLED_0_RED = 0;
    data->SIGOUT_BOARD0_STEPDIR0_VELOCITY_SCALE = (float*)malloc(sizeof(float));
    *data->SIGOUT_BOARD0_STEPDIR0_VELOCITY_SCALE = 1.0;
    data->SIGOUT_BOARD0_STEPDIR0_VELOCITY_OFFSET = (float*)malloc(sizeof(float));
    *data->SIGOUT_BOARD0_STEPDIR0_VELOCITY_OFFSET = 0.0;
    data->SIGOUT_BOARD0_STEPDIR0_VELOCITY = (float*)malloc(sizeof(float));
    *data->SIGOUT_BOARD0_STEPDIR0_VELOCITY = 0;
    data->SIGIN_BOARD0_STEPDIR0_POSITION_SCALE = (float*)malloc(sizeof(float));
    *data->SIGIN_BOARD0_STEPDIR0_POSITION_SCALE = 1.0;
    data->SIGIN_BOARD0_STEPDIR0_POSITION_OFFSET = (float*)malloc(sizeof(float));
    *data->SIGIN_BOARD0_STEPDIR0_POSITION_OFFSET = 0.0;
    data->SIGIN_BOARD0_STEPDIR0_POSITION = (float*)malloc(sizeof(float));
    *data->SIGIN_BOARD0_STEPDIR0_POSITION = 0;
    data->SIGIN_BOARD0_STEPDIR0_POSITION_ABS = (float*)malloc(sizeof(float));
    *data->SIGIN_BOARD0_STEPDIR0_POSITION_ABS = 0;
    data->SIGIN_BOARD0_STEPDIR0_POSITION_S32 = (int32_t*)malloc(sizeof(int32_t));
    *data->SIGIN_BOARD0_STEPDIR0_POSITION_S32 = 0;
    data->SIGIN_BOARD0_STEPDIR0_POSITION_U32_ABS = (uint32_t*)malloc(sizeof(uint32_t));
    *data->SIGIN_BOARD0_STEPDIR0_POSITION_U32_ABS = 0;
    data->SIGOUT_BOARD0_STEPDIR0_ENABLE = (bool*)malloc(sizeof(bool));
    *data->SIGOUT_BOARD0_STEPDIR0_ENABLE = 0;
    data->SIGOUT_BOARD0_STEPDIR1_VELOCITY_SCALE = (float*)malloc(sizeof(float));
    *data->SIGOUT_BOARD0_STEPDIR1_VELOCITY_SCALE = 1.0;
    data->SIGOUT_BOARD0_STEPDIR1_VELOCITY_OFFSET = (float*)malloc(sizeof(float));
    *data->SIGOUT_BOARD0_STEPDIR1_VELOCITY_OFFSET = 0.0;
    data->SIGOUT_BOARD0_STEPDIR1_VELOCITY = (float*)malloc(sizeof(float));
    *data->SIGOUT_BOARD0_STEPDIR1_VELOCITY = 0;
    data->SIGIN_BOARD0_STEPDIR1_POSITION_SCALE = (float*)malloc(sizeof(float));
    *data->SIGIN_BOARD0_STEPDIR1_POSITION_SCALE = 1.0;
    data->SIGIN_BOARD0_STEPDIR1_POSITION_OFFSET = (float*)malloc(sizeof(float));
    *data->SIGIN_BOARD0_STEPDIR1_POSITION_OFFSET = 0.0;
    data->SIGIN_BOARD0_STEPDIR1_POSITION = (float*)malloc(sizeof(float));
    *data->SIGIN_BOARD0_STEPDIR1_POSITION = 0;
    data->SIGIN_BOARD0_STEPDIR1_POSITION_ABS = (float*)malloc(sizeof(float));
    *data->SIGIN_BOARD0_STEPDIR1_POSITION_ABS = 0;
    data->SIGIN_BOARD0_STEPDIR1_POSITION_S32 = (int32_t*)malloc(sizeof(int32_t));
    *data->SIGIN_BOARD0_STEPDIR1_POSITION_S32 = 0;
    data->SIGIN_BOARD0_STEPDIR1_POSITION_U32_ABS = (uint32_t*)malloc(sizeof(uint32_t));
    *data->SIGIN_BOARD0_STEPDIR1_POSITION_U32_ABS = 0;
    data->SIGOUT_BOARD0_STEPDIR1_ENABLE = (bool*)malloc(sizeof(bool));
    *data->SIGOUT_BOARD0_STEPDIR1_ENABLE = 0;
    data->SIGOUT_BOARD0_STEPDIR2_VELOCITY_SCALE = (float*)malloc(sizeof(float));
    *data->SIGOUT_BOARD0_STEPDIR2_VELOCITY_SCALE = 1.0;
    data->SIGOUT_BOARD0_STEPDIR2_VELOCITY_OFFSET = (float*)malloc(sizeof(float));
    *data->SIGOUT_BOARD0_STEPDIR2_VELOCITY_OFFSET = 0.0;
    data->SIGOUT_BOARD0_STEPDIR2_VELOCITY = (float*)malloc(sizeof(float));
    *data->SIGOUT_BOARD0_STEPDIR2_VELOCITY = 0;
    data->SIGIN_BOARD0_STEPDIR2_POSITION_SCALE = (float*)malloc(sizeof(float));
    *data->SIGIN_BOARD0_STEPDIR2_POSITION_SCALE = 1.0;
    data->SIGIN_BOARD0_STEPDIR2_POSITION_OFFSET = (float*)malloc(sizeof(float));
    *data->SIGIN_BOARD0_STEPDIR2_POSITION_OFFSET = 0.0;
    data->SIGIN_BOARD0_STEPDIR2_POSITION = (float*)malloc(sizeof(float));
    *data->SIGIN_BOARD0_STEPDIR2_POSITION = 0;
    data->SIGIN_BOARD0_STEPDIR2_POSITION_ABS = (float*)malloc(sizeof(float));
    *data->SIGIN_BOARD0_STEPDIR2_POSITION_ABS = 0;
    data->SIGIN_BOARD0_STEPDIR2_POSITION_S32 = (int32_t*)malloc(sizeof(int32_t));
    *data->SIGIN_BOARD0_STEPDIR2_POSITION_S32 = 0;
    data->SIGIN_BOARD0_STEPDIR2_POSITION_U32_ABS = (uint32_t*)malloc(sizeof(uint32_t));
    *data->SIGIN_BOARD0_STEPDIR2_POSITION_U32_ABS = 0;
    data->SIGOUT_BOARD0_STEPDIR2_ENABLE = (bool*)malloc(sizeof(bool));
    *data->SIGOUT_BOARD0_STEPDIR2_ENABLE = 0;
}

/*
    interface: UDP
*/

#include <string.h>
#include <stdio.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>

#define SEND_TIMEOUT_US 10
#define RECV_TIMEOUT_US 10
#define READ_PCK_DELAY_NS 1000
#define READ_PCK_TIMEOUT_MS 2

static int udpSocket;
static int errCount;
struct sockaddr_in dstAddr, srcAddr;
struct hostent *server;

int udp_init(const char *dstAddress, int dstPort, int srcPort) {
    int ret;

    // Create a UDP socket
    udpSocket = socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP);
    if (udpSocket < 0) {
        printf("ERROR: can't open socket: %s\n", "error");
        return -1;
    }

    bzero((char*) &dstAddr, sizeof(dstAddr));
    dstAddr.sin_family = AF_INET;
    dstAddr.sin_addr.s_addr = inet_addr(dstAddress);
    dstAddr.sin_port = htons(dstPort);

    bzero((char*) &srcAddr, sizeof(srcAddr));
    srcAddr.sin_family = AF_INET;
    srcAddr.sin_addr.s_addr = htonl(INADDR_ANY);
    srcAddr.sin_port = htons(srcPort);

    printf("INFO: target is udp port: %s:%i\n", dstAddress, dstPort);
    printf("INFO: listening on udp port: %s:%i\n", "0.0.0.0", srcPort);

    // bind the local socket to SCR_PORT
    ret = bind(udpSocket, (struct sockaddr *) &srcAddr, sizeof(srcAddr));
    if (ret < 0) {
        printf("ERROR: can't bind: %s\n", "error");
        return -1;
    }

    // Connect to send and receive only to the server_addr
    ret = connect(udpSocket, (struct sockaddr*) &dstAddr, sizeof(struct sockaddr_in));
    if (ret < 0) {
        printf("ERROR: can't connect: %s\n", "error");
        return -1;
    }

    struct timeval timeout;
    timeout.tv_sec = 0;
    timeout.tv_usec = RECV_TIMEOUT_US;

    ret = setsockopt(udpSocket, SOL_SOCKET, SO_RCVTIMEO, (char*) &timeout, sizeof(timeout));
    if (ret < 0) {
        printf("ERROR: can't set receive timeout socket option: %s\n", "error");
        return -1;
    }

    timeout.tv_usec = SEND_TIMEOUT_US;
    ret = setsockopt(udpSocket, SOL_SOCKET, SO_SNDTIMEO, (char*) &timeout,
                     sizeof(timeout));
    if (ret < 0) {
        printf("ERROR: can't set send timeout socket option: %s\n", "error");
        return -1;
    }

    return 0;
}

void udp_tx(uint8_t *txBuffer, uint16_t size) {
    // Send datagram
    send(udpSocket, txBuffer, size, 0);
}

int udp_rx(uint8_t *rxBuffer, uint16_t size, uint8_t udp_async) {
    int i;
    int ret;
    long t1;
    long t2;
    uint8_t rxBufferTmp[1024];

    for (i = 0; i < 1024; i++) {
        rxBufferTmp[i] = 0;
    }

    // Receive incoming datagram
    if (udp_async == 1) {
        ret = recv(udpSocket, rxBufferTmp, size * 2, MSG_DONTWAIT);
    } else {
        t1 = rtapi_get_time();
        do {
            ret = recv(udpSocket, rxBufferTmp, size * 2, 0);
            if (ret < 0) {
                rtapi_delay(READ_PCK_DELAY_NS);
            }
            t2 = rtapi_get_time();
        }
        while ((ret < 0) && ((t2 - t1) < READ_PCK_TIMEOUT_MS * 1000 * 1000));
    }

    if (ret > 0) {
        errCount = 0;
        if (ret == size) {
            memcpy(rxBuffer, rxBufferTmp, size);
        } else {
            printf("wrong size = %d\n", ret);
            for (i = 0; i < ret; i++) {
                printf("%d ", rxBufferTmp[i]);
            }
            printf("\n");
        }
        /*
        printf("rx:");
        for (i = 0; i < ret; i++) {
            printf(" %d,", rxBuffer[i]);
        }
        printf("\n");
        */
    } else {
        errCount++;
        // printf("Ethernet TIMEOUT: N = %d (ret: %d)\n", errCount, ret);
    }

    return ret;
}

void udp_exit(void) {
}

int interface_init(int argc, char **argv) {
    char* dstAddress[1024];
    int dstPort = DST_PORT;
    if (argc > 1) {
        int ip0 = 0;
        int ip1 = 0;
        int ip2 = 0;
        int ip3 = 0;
        int port = 0;
        int ret = sscanf(argv[1], "%d.%d.%d.%d:%d", &ip0, &ip1, &ip2, &ip3, &port);
        if (ret >= 4) {
            sprintf(dstAddress, "%d.%d.%d.%d", ip0, ip1, ip2, ip3);
            if (ret == 5) {
                dstPort = port;
            }
        }
        udp_init(dstAddress, dstPort, SRC_PORT);
    } else {
        udp_init(UDP_IP, DST_PORT, SRC_PORT);
    }
    return 0;
}

void interface_exit(void) {
    udp_exit();
}


/*
    hal functions
*/

/***********************************************************************
*                       HELPER FUNCTIONS                               *
************************************************************************/

uint16_t crc16_update(uint16_t crc, uint8_t a) {
	int i;

	crc ^= (uint16_t)a;
	for (i = 0; i < 8; ++i) {
		if (crc & 1)
			crc = (crc >> 1) ^ 0xA001;
		else
			crc = (crc >> 1);
	}

	return crc;
}


/***********************************************************************/


/***********************************************************************
*                         PLUGIN GLOBALS                               *
************************************************************************/








/***********************************************************************/

// Generated by component_signal_converter()
// output: SIGOUT -> calc -> VAROUT -> txBuffer
void convert_varout1_board0_wled_0_green(data_t *data){
    bool value = *data->SIGOUT_BOARD0_BOARD0_WLED_0_GREEN;
    
    data->VAROUT1_BOARD0_WLED_0_GREEN = value;
}

void convert_varout1_board0_wled_0_blue(data_t *data){
    bool value = *data->SIGOUT_BOARD0_BOARD0_WLED_0_BLUE;
    
    data->VAROUT1_BOARD0_WLED_0_BLUE = value;
}

void convert_varout1_board0_wled_0_red(data_t *data){
    bool value = *data->SIGOUT_BOARD0_BOARD0_WLED_0_RED;
    
    data->VAROUT1_BOARD0_WLED_0_RED = value;
}

void convert_varout32_stepdir0_velocity(data_t *data){
    float value = *data->SIGOUT_BOARD0_STEPDIR0_VELOCITY;
    value = value * *data->SIGOUT_BOARD0_STEPDIR0_VELOCITY_SCALE;
    value = value + *data->SIGOUT_BOARD0_STEPDIR0_VELOCITY_OFFSET;
    if (value != 0) {
                value = OSC_CLOCK / value / 2;
            }
    data->VAROUT32_STEPDIR0_VELOCITY = value;
}

void convert_varout1_stepdir0_enable(data_t *data){
    bool value = *data->SIGOUT_BOARD0_STEPDIR0_ENABLE;
    
    data->VAROUT1_STEPDIR0_ENABLE = value;
}

void convert_varout32_stepdir1_velocity(data_t *data){
    float value = *data->SIGOUT_BOARD0_STEPDIR1_VELOCITY;
    value = value * *data->SIGOUT_BOARD0_STEPDIR1_VELOCITY_SCALE;
    value = value + *data->SIGOUT_BOARD0_STEPDIR1_VELOCITY_OFFSET;
    if (value != 0) {
                value = OSC_CLOCK / value / 2;
            }
    data->VAROUT32_STEPDIR1_VELOCITY = value;
}

void convert_varout1_stepdir1_enable(data_t *data){
    bool value = *data->SIGOUT_BOARD0_STEPDIR1_ENABLE;
    
    data->VAROUT1_STEPDIR1_ENABLE = value;
}

void convert_varout32_stepdir2_velocity(data_t *data){
    float value = *data->SIGOUT_BOARD0_STEPDIR2_VELOCITY;
    value = value * *data->SIGOUT_BOARD0_STEPDIR2_VELOCITY_SCALE;
    value = value + *data->SIGOUT_BOARD0_STEPDIR2_VELOCITY_OFFSET;
    if (value != 0) {
                value = OSC_CLOCK / value / 2;
            }
    data->VAROUT32_STEPDIR2_VELOCITY = value;
}

void convert_varout1_stepdir2_enable(data_t *data){
    bool value = *data->SIGOUT_BOARD0_STEPDIR2_ENABLE;
    
    data->VAROUT1_STEPDIR2_ENABLE = value;
}


// input: rxBuffer -> VAROUT -> calc -> SIGOUT
void convert_sigin_board0_stepdir0_position(data_t *data) {
    float value = data->VARIN32_STEPDIR0_POSITION;
    float offset = *data->SIGIN_BOARD0_STEPDIR0_POSITION_OFFSET;
    float scale = *data->SIGIN_BOARD0_STEPDIR0_POSITION_SCALE;
    float last_value = *data->SIGIN_BOARD0_STEPDIR0_POSITION;
    static float last_raw_value = 0.0;
    float raw_value = value;
    value = value + offset;
    value = value / scale;
    if (*data->sys_simulation == 1) {
        value = *data->SIGIN_BOARD0_STEPDIR0_POSITION + *data->SIGOUT_BOARD0_STEPDIR0_VELOCITY / 1000.0;
    }
    *data->SIGIN_BOARD0_STEPDIR0_POSITION_ABS = abs(value);
    *data->SIGIN_BOARD0_STEPDIR0_POSITION_S32 = value;
    *data->SIGIN_BOARD0_STEPDIR0_POSITION_U32_ABS = abs(value);
    *data->SIGIN_BOARD0_STEPDIR0_POSITION = value;

    last_raw_value = raw_value;
}

void convert_sigin_board0_stepdir1_position(data_t *data) {
    float value = data->VARIN32_STEPDIR1_POSITION;
    float offset = *data->SIGIN_BOARD0_STEPDIR1_POSITION_OFFSET;
    float scale = *data->SIGIN_BOARD0_STEPDIR1_POSITION_SCALE;
    float last_value = *data->SIGIN_BOARD0_STEPDIR1_POSITION;
    static float last_raw_value = 0.0;
    float raw_value = value;
    value = value + offset;
    value = value / scale;
    if (*data->sys_simulation == 1) {
        value = *data->SIGIN_BOARD0_STEPDIR1_POSITION + *data->SIGOUT_BOARD0_STEPDIR1_VELOCITY / 1000.0;
    }
    *data->SIGIN_BOARD0_STEPDIR1_POSITION_ABS = abs(value);
    *data->SIGIN_BOARD0_STEPDIR1_POSITION_S32 = value;
    *data->SIGIN_BOARD0_STEPDIR1_POSITION_U32_ABS = abs(value);
    *data->SIGIN_BOARD0_STEPDIR1_POSITION = value;

    last_raw_value = raw_value;
}

void convert_sigin_board0_stepdir2_position(data_t *data) {
    float value = data->VARIN32_STEPDIR2_POSITION;
    float offset = *data->SIGIN_BOARD0_STEPDIR2_POSITION_OFFSET;
    float scale = *data->SIGIN_BOARD0_STEPDIR2_POSITION_SCALE;
    float last_value = *data->SIGIN_BOARD0_STEPDIR2_POSITION;
    static float last_raw_value = 0.0;
    float raw_value = value;
    value = value + offset;
    value = value / scale;
    if (*data->sys_simulation == 1) {
        value = *data->SIGIN_BOARD0_STEPDIR2_POSITION + *data->SIGOUT_BOARD0_STEPDIR2_VELOCITY / 1000.0;
    }
    *data->SIGIN_BOARD0_STEPDIR2_POSITION_ABS = abs(value);
    *data->SIGIN_BOARD0_STEPDIR2_POSITION_S32 = value;
    *data->SIGIN_BOARD0_STEPDIR2_POSITION_U32_ABS = abs(value);
    *data->SIGIN_BOARD0_STEPDIR2_POSITION = value;

    last_raw_value = raw_value;
}



// Generated by component_buffer_converter()
void convert_outputs(void) {
    // output loop: SIGOUT -> calc -> VAROUT -> txBuffer
    convert_varout1_board0_wled_0_green(data);
    convert_varout1_board0_wled_0_blue(data);
    convert_varout1_board0_wled_0_red(data);
    convert_varout32_stepdir0_velocity(data);
    convert_varout1_stepdir0_enable(data);
    convert_varout32_stepdir1_velocity(data);
    convert_varout1_stepdir1_enable(data);
    convert_varout32_stepdir2_velocity(data);
    convert_varout1_stepdir2_enable(data);
}

void convert_inputs(void) {
    // input: rxBuffer -> VAROUT -> calc -> SIGOUT
    convert_sigin_board0_stepdir0_position(data);
    convert_sigin_board0_stepdir1_position(data);
    convert_sigin_board0_stepdir2_position(data);
}

// Generated by component_buffer()
void write_txbuffer(uint8_t *txBuffer) {
    // PC -> FPGA (134 + 26)
    int i = 0;
    for (i = 0; i < BUFFER_SIZE; i++) {
        txBuffer[i] = 0;
    }
    // raw vars to txBuffer
    txBuffer[0] = 0x74; // 160
    txBuffer[1] = 0x69; // 152
    txBuffer[2] = 0x72; // 144
    txBuffer[3] = 0x77; // 136
    memcpy(&txBuffer[4], &data->VAROUT32_STEPDIR0_VELOCITY, 4); // 128
    memcpy(&txBuffer[8], &data->VAROUT32_STEPDIR1_VELOCITY, 4); // 96
    memcpy(&txBuffer[12], &data->VAROUT32_STEPDIR2_VELOCITY, 4); // 64
    txBuffer[16] |= (data->VAROUT1_BOARD0_WLED_0_GREEN<<7); // 32
    txBuffer[16] |= (data->VAROUT1_BOARD0_WLED_0_BLUE<<6); // 31
    txBuffer[16] |= (data->VAROUT1_BOARD0_WLED_0_RED<<5); // 30
    txBuffer[16] |= (data->VAROUT1_STEPDIR0_ENABLE<<4); // 29
    txBuffer[16] |= (data->VAROUT1_STEPDIR1_ENABLE<<3); // 28
    txBuffer[16] |= (data->VAROUT1_STEPDIR2_ENABLE<<2); // 27
    // FILL: 26
}

void read_rxbuffer(uint8_t *rxBuffer) {
    // FPGA -> PC (160 + 0)
    // memcpy(&header, &rxBuffer[0], 4) // 160;
    memcpy(&fpga_timestamp, &rxBuffer[4], 4); // 128
    memcpy(&data->VARIN32_STEPDIR0_POSITION, &rxBuffer[8], 4); // 96
    memcpy(&data->VARIN32_STEPDIR1_POSITION, &rxBuffer[12], 4); // 64
    memcpy(&data->VARIN32_STEPDIR2_POSITION, &rxBuffer[16], 4); // 32
    // FILL: 0
}

void rio_readwrite(void *inst, long period) {
    int ret = 0;
    uint8_t i = 0;
    uint8_t rxBuffer[BUFFER_SIZE * 2];
    uint8_t txBuffer[BUFFER_SIZE * 2];
    if (*data->sys_enable_request == 1) {
        *data->sys_status = 1;
    }
    long stamp_new = rtapi_get_time();
    float duration2 = (stamp_new - stamp_last) / 1000.0;
    stamp_last = stamp_new;
    float timestamp = (float)fpga_timestamp / (float)OSC_CLOCK;
    *data->duration = timestamp - fpga_stamp_last;
    fpga_stamp_last = timestamp;
    if (1) {
        pkg_counter += 1;
        convert_outputs();
        if (*data->sys_simulation != 1) {
            write_txbuffer(txBuffer);
#ifdef UDP_ASYNC
            ret = udp_rx(rxBuffer, BUFFER_SIZE, 1);
            udp_tx(txBuffer, BUFFER_SIZE);
#else
            udp_tx(txBuffer, BUFFER_SIZE);
            ret = udp_rx(rxBuffer, BUFFER_SIZE, 0);
#endif
            if (ret == BUFFER_SIZE && rxBuffer[0] == 97 && rxBuffer[1] == 116 && rxBuffer[2] == 97 && rxBuffer[3] == 100) {
                if (err_counter > 0) {
                    err_counter = 0;
                    printf("recovered..\n");
                }
                read_rxbuffer(rxBuffer);
                convert_inputs();
            } else {
                err_counter += 1;
                err_total += 1;
                if (ret != BUFFER_SIZE) {
                    printf("%i: wrong data size (len %i/%i err %i/3) - (%i %i - %0.4f %%)", stamp_new, ret, BUFFER_SIZE, err_counter, err_total, pkg_counter, (float)err_total * 100.0 / (float)pkg_counter);
                } else {
                    printf("%i: wrong header (%i/3) - (%i %i - %0.4f %%):", stamp_new, err_counter, err_total, pkg_counter, (float)err_total * 100.0 / (float)pkg_counter);
                }
                for (i = 0; i < ret; i++) {
                    printf("%d ",rxBuffer[i]);
                }
                printf("\n");
                if (err_counter > 3) {
                    printf("too many errors..\n");
                    *data->sys_status = 0;
                }
            }
        } else {
            convert_inputs();
        }
    } else {
        *data->sys_status = 0;
    }
}


void cb_SIGOUT_BOARD0_BOARD0_WLED_0_GREEN(const std_msgs::Bool::ConstPtr& msg) {
    *data->SIGOUT_BOARD0_BOARD0_WLED_0_GREEN = msg->data;
}

void cb_SIGOUT_BOARD0_BOARD0_WLED_0_BLUE(const std_msgs::Bool::ConstPtr& msg) {
    *data->SIGOUT_BOARD0_BOARD0_WLED_0_BLUE = msg->data;
}

void cb_SIGOUT_BOARD0_BOARD0_WLED_0_RED(const std_msgs::Bool::ConstPtr& msg) {
    *data->SIGOUT_BOARD0_BOARD0_WLED_0_RED = msg->data;
}

void cb_SIGOUT_BOARD0_STEPDIR0_VELOCITY(const std_msgs::Float32::ConstPtr& msg) {
    *data->SIGOUT_BOARD0_STEPDIR0_VELOCITY = msg->data;
}

void cb_SIGOUT_BOARD0_STEPDIR0_ENABLE(const std_msgs::Bool::ConstPtr& msg) {
    *data->SIGOUT_BOARD0_STEPDIR0_ENABLE = msg->data;
}

void cb_SIGOUT_BOARD0_STEPDIR1_VELOCITY(const std_msgs::Float32::ConstPtr& msg) {
    *data->SIGOUT_BOARD0_STEPDIR1_VELOCITY = msg->data;
}

void cb_SIGOUT_BOARD0_STEPDIR1_ENABLE(const std_msgs::Bool::ConstPtr& msg) {
    *data->SIGOUT_BOARD0_STEPDIR1_ENABLE = msg->data;
}

void cb_SIGOUT_BOARD0_STEPDIR2_VELOCITY(const std_msgs::Float32::ConstPtr& msg) {
    *data->SIGOUT_BOARD0_STEPDIR2_VELOCITY = msg->data;
}

void cb_SIGOUT_BOARD0_STEPDIR2_ENABLE(const std_msgs::Bool::ConstPtr& msg) {
    *data->SIGOUT_BOARD0_STEPDIR2_ENABLE = msg->data;
}


int main(int argc, char **argv) {

    ros::init(argc, argv, "riobridge");

    data = (data_t*)malloc(sizeof(data_t));
    register_signals();
    interface_init();

    ros::NodeHandle nSIGOUT_BOARD0_BOARD0_WLED_0_GREEN;
    ros::Subscriber sub_SIGOUT_BOARD0_BOARD0_WLED_0_GREEN = nSIGOUT_BOARD0_BOARD0_WLED_0_GREEN.subscribe("board0/board0/board0_wled/0_green", 1000, cb_SIGOUT_BOARD0_BOARD0_WLED_0_GREEN);
    ros::NodeHandle nSIGOUT_BOARD0_BOARD0_WLED_0_BLUE;
    ros::Subscriber sub_SIGOUT_BOARD0_BOARD0_WLED_0_BLUE = nSIGOUT_BOARD0_BOARD0_WLED_0_BLUE.subscribe("board0/board0/board0_wled/0_blue", 1000, cb_SIGOUT_BOARD0_BOARD0_WLED_0_BLUE);
    ros::NodeHandle nSIGOUT_BOARD0_BOARD0_WLED_0_RED;
    ros::Subscriber sub_SIGOUT_BOARD0_BOARD0_WLED_0_RED = nSIGOUT_BOARD0_BOARD0_WLED_0_RED.subscribe("board0/board0/board0_wled/0_red", 1000, cb_SIGOUT_BOARD0_BOARD0_WLED_0_RED);
    ros::NodeHandle nSIGOUT_BOARD0_STEPDIR0_VELOCITY;
    ros::Subscriber sub_SIGOUT_BOARD0_STEPDIR0_VELOCITY = nSIGOUT_BOARD0_STEPDIR0_VELOCITY.subscribe("board0/board0/stepdir0/velocity", 1000, cb_SIGOUT_BOARD0_STEPDIR0_VELOCITY);
    ros::NodeHandle nSIGIN_BOARD0_STEPDIR0_POSITION;
    std_msgs::Float32 msg_SIGIN_BOARD0_STEPDIR0_POSITION;
    ros::Publisher pub_SIGIN_BOARD0_STEPDIR0_POSITION = nSIGIN_BOARD0_STEPDIR0_POSITION.advertise<std_msgs::Float32>("board0/board0/stepdir0/position", 1000);
    ros::NodeHandle nSIGOUT_BOARD0_STEPDIR0_ENABLE;
    ros::Subscriber sub_SIGOUT_BOARD0_STEPDIR0_ENABLE = nSIGOUT_BOARD0_STEPDIR0_ENABLE.subscribe("board0/board0/stepdir0/enable", 1000, cb_SIGOUT_BOARD0_STEPDIR0_ENABLE);
    ros::NodeHandle nSIGOUT_BOARD0_STEPDIR1_VELOCITY;
    ros::Subscriber sub_SIGOUT_BOARD0_STEPDIR1_VELOCITY = nSIGOUT_BOARD0_STEPDIR1_VELOCITY.subscribe("board0/board0/stepdir1/velocity", 1000, cb_SIGOUT_BOARD0_STEPDIR1_VELOCITY);
    ros::NodeHandle nSIGIN_BOARD0_STEPDIR1_POSITION;
    std_msgs::Float32 msg_SIGIN_BOARD0_STEPDIR1_POSITION;
    ros::Publisher pub_SIGIN_BOARD0_STEPDIR1_POSITION = nSIGIN_BOARD0_STEPDIR1_POSITION.advertise<std_msgs::Float32>("board0/board0/stepdir1/position", 1000);
    ros::NodeHandle nSIGOUT_BOARD0_STEPDIR1_ENABLE;
    ros::Subscriber sub_SIGOUT_BOARD0_STEPDIR1_ENABLE = nSIGOUT_BOARD0_STEPDIR1_ENABLE.subscribe("board0/board0/stepdir1/enable", 1000, cb_SIGOUT_BOARD0_STEPDIR1_ENABLE);
    ros::NodeHandle nSIGOUT_BOARD0_STEPDIR2_VELOCITY;
    ros::Subscriber sub_SIGOUT_BOARD0_STEPDIR2_VELOCITY = nSIGOUT_BOARD0_STEPDIR2_VELOCITY.subscribe("board0/board0/stepdir2/velocity", 1000, cb_SIGOUT_BOARD0_STEPDIR2_VELOCITY);
    ros::NodeHandle nSIGIN_BOARD0_STEPDIR2_POSITION;
    std_msgs::Float32 msg_SIGIN_BOARD0_STEPDIR2_POSITION;
    ros::Publisher pub_SIGIN_BOARD0_STEPDIR2_POSITION = nSIGIN_BOARD0_STEPDIR2_POSITION.advertise<std_msgs::Float32>("board0/board0/stepdir2/position", 1000);
    ros::NodeHandle nSIGOUT_BOARD0_STEPDIR2_ENABLE;
    ros::Subscriber sub_SIGOUT_BOARD0_STEPDIR2_ENABLE = nSIGOUT_BOARD0_STEPDIR2_ENABLE.subscribe("board0/board0/stepdir2/enable", 1000, cb_SIGOUT_BOARD0_STEPDIR2_ENABLE);


    ros::Rate loop_rate(10);

    while (ros::ok()) {
        rio_readwrite(NULL, 0);

        msg_SIGIN_BOARD0_STEPDIR0_POSITION.data = *data->SIGIN_BOARD0_STEPDIR0_POSITION;
        pub_SIGIN_BOARD0_STEPDIR0_POSITION.publish(msg_SIGIN_BOARD0_STEPDIR0_POSITION);

        msg_SIGIN_BOARD0_STEPDIR1_POSITION.data = *data->SIGIN_BOARD0_STEPDIR1_POSITION;
        pub_SIGIN_BOARD0_STEPDIR1_POSITION.publish(msg_SIGIN_BOARD0_STEPDIR1_POSITION);

        msg_SIGIN_BOARD0_STEPDIR2_POSITION.data = *data->SIGIN_BOARD0_STEPDIR2_POSITION;
        pub_SIGIN_BOARD0_STEPDIR2_POSITION.publish(msg_SIGIN_BOARD0_STEPDIR2_POSITION);


        ros::spinOnce();
        loop_rate.sleep();
    }

    return 0;
}
