# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/buildbot/buildbot/worker/turbonc/sources/debian/python3-turbonc/usr/lib/python3.11/dist-packages/tnc/dialogs/zero_xy.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(384, 247)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.statuslabel = StatusLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statuslabel.sizePolicy().hasHeightForWidth())
        self.statuslabel.setSizePolicy(sizePolicy)
        self.statuslabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statuslabel.setObjectName("statuslabel")
        self.verticalLayout_2.addWidget(self.statuslabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, 0, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.close_button = QtWidgets.QPushButton(Dialog)
        self.close_button.setMaximumSize(QtCore.QSize(72, 64))
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_2.addWidget(self.close_button)
        self.zero_xy_button = MDIButton(Dialog)
        self.zero_xy_button.setEnabled(False)
        self.zero_xy_button.setMaximumSize(QtCore.QSize(72, 64))
        self.zero_xy_button.setObjectName("zero_xy_button")
        self.horizontalLayout_2.addWidget(self.zero_xy_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Frame"))
        self.statuslabel.setText(_translate("Dialog", "Do you want to set X and Y to ZERO?\n" " WCS G53 P0"))
        self.statuslabel.setProperty(
            "rules",
            _translate(
                "Dialog",
                '[{"channels": [{"url": "status:g5x_index", "trigger": true}], "property": "Text", "expression": "\\"Do you want to set X and Y to ZERO?\\\\n WCS G5{} P{}\\".format(3+ch[0], ch[0])", "name": "Active WCS"}]',
            ),
        )
        self.close_button.setText(_translate("Dialog", "CLOSE"))
        self.zero_xy_button.setText(_translate("Dialog", "OK"))
        self.zero_xy_button.setProperty(
            "rules",
            _translate(
                "Dialog",
                "[\n"
                "    {\n"
                '        "channels": [\n'
                "            {\n"
                '                "url": "status:g5x_index",\n'
                '                "trigger": true,\n'
                '                "type": "int"\n'
                "            }\n"
                "        ],\n"
                '        "expression": "",\n'
                '        "name": "G5x Index",\n'
                '        "property": "None"\n'
                "    }\n"
                "]",
            ),
        )
        self.zero_xy_button.setProperty("MDICommand", _translate("Dialog", "G10 L20 P{ch[0]} X0.0 Y0.0"))


from qtpyvcp.widgets.button_widgets.mdi_button import MDIButton
from qtpyvcp.widgets.display_widgets.status_label import StatusLabel
