// Generated by rio-generator
#include <rtapi.h>
#include <rtapi_app.h>
#include <hal.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <sys/mman.h>
#include <errno.h>
#include <fcntl.h>
#include <termios.h>

MODULE_AUTHOR("Oliver Dippel");
MODULE_DESCRIPTION("Driver for RIO FPGA boards");
MODULE_LICENSE("GPL v2");

#define MODNAME "riocomp-board0"
#define PREFIX "board0"
#define JOINTS 3
#define BUFFER_SIZE 21
#define OSC_CLOCK 30000000
#define UDP_IP "192.168.11.194"
#define SRC_PORT 2391
#define DST_PORT 2390
#define SERIAL_PORT "/dev/ttyUSB1"
#define SERIAL_BAUD B1000000
#define SPI_PIN_MOSI 10
#define SPI_PIN_MISO 9
#define SPI_PIN_CLK 11
#define SPI_PIN_CS 8
#define SPI_SPEED BCM2835_SPI_CLOCK_DIVIDER_256

static int 			      comp_id;
static const char 	      *modname = MODNAME;
static const char 	      *prefix = PREFIX;

uint32_t pkg_counter = 0;
uint32_t err_total = 0;
uint32_t err_counter = 0;

long stamp_last = 0;
float fpga_stamp_last = 0;
uint32_t fpga_timestamp = 0;

void rio_readwrite(void *inst, long period);
int error_handler(int retval);

typedef struct {
    // hal variables
    hal_bit_t   *sys_enable;
    hal_bit_t   *sys_enable_request;
    hal_bit_t   *sys_status;
    hal_bit_t   *machine_on;
    hal_bit_t   *sys_simulation;
    hal_u32_t   *fpga_timestamp;
    hal_float_t *duration;
    hal_float_t *SIGOUT_BOARD0_STEPDIR0_VELOCITY;
    hal_float_t *SIGOUT_BOARD0_STEPDIR0_VELOCITY_SCALE;
    hal_float_t *SIGOUT_BOARD0_STEPDIR0_VELOCITY_OFFSET;
    hal_float_t *SIGIN_BOARD0_STEPDIR0_POSITION;
    hal_float_t *SIGIN_BOARD0_STEPDIR0_POSITION_ABS;
    hal_s32_t *SIGIN_BOARD0_STEPDIR0_POSITION_S32;
    hal_u32_t *SIGIN_BOARD0_STEPDIR0_POSITION_U32_ABS;
    hal_float_t *SIGIN_BOARD0_STEPDIR0_POSITION_SCALE;
    hal_float_t *SIGIN_BOARD0_STEPDIR0_POSITION_OFFSET;
    hal_bit_t   *SIGOUT_BOARD0_STEPDIR0_ENABLE;
    hal_float_t *SIGOUT_BOARD0_STEPDIR1_VELOCITY;
    hal_float_t *SIGOUT_BOARD0_STEPDIR1_VELOCITY_SCALE;
    hal_float_t *SIGOUT_BOARD0_STEPDIR1_VELOCITY_OFFSET;
    hal_float_t *SIGIN_BOARD0_STEPDIR1_POSITION;
    hal_float_t *SIGIN_BOARD0_STEPDIR1_POSITION_ABS;
    hal_s32_t *SIGIN_BOARD0_STEPDIR1_POSITION_S32;
    hal_u32_t *SIGIN_BOARD0_STEPDIR1_POSITION_U32_ABS;
    hal_float_t *SIGIN_BOARD0_STEPDIR1_POSITION_SCALE;
    hal_float_t *SIGIN_BOARD0_STEPDIR1_POSITION_OFFSET;
    hal_bit_t   *SIGOUT_BOARD0_STEPDIR1_ENABLE;
    hal_bit_t   *SIGIN_BOARD0_BITIN0_BIT;
    hal_bit_t   *SIGIN_BOARD0_BITIN0_BIT_not;
    hal_float_t *SIGOUT_BOARD0_STEPDIR2_VELOCITY;
    hal_float_t *SIGOUT_BOARD0_STEPDIR2_VELOCITY_SCALE;
    hal_float_t *SIGOUT_BOARD0_STEPDIR2_VELOCITY_OFFSET;
    hal_float_t *SIGIN_BOARD0_STEPDIR2_POSITION;
    hal_float_t *SIGIN_BOARD0_STEPDIR2_POSITION_ABS;
    hal_s32_t *SIGIN_BOARD0_STEPDIR2_POSITION_S32;
    hal_u32_t *SIGIN_BOARD0_STEPDIR2_POSITION_U32_ABS;
    hal_float_t *SIGIN_BOARD0_STEPDIR2_POSITION_SCALE;
    hal_float_t *SIGIN_BOARD0_STEPDIR2_POSITION_OFFSET;
    hal_bit_t   *SIGOUT_BOARD0_STEPDIR2_ENABLE;
    hal_bit_t   *SIGOUT_BOARD0_BITOUT0_BIT;
    hal_bit_t   *SIGOUT_BOARD0_BITOUT1_BIT;
    hal_bit_t   *SIGIN_BOARD0_BITIN1_BIT;
    hal_bit_t   *SIGIN_BOARD0_BITIN1_BIT_not;
    hal_bit_t   *SIGIN_BOARD0_BITIN2_BIT;
    hal_bit_t   *SIGIN_BOARD0_BITIN2_BIT_not;
    hal_bit_t   *SIGIN_BOARD0_BITIN3_BIT;
    hal_bit_t   *SIGIN_BOARD0_BITIN3_BIT_not;
    hal_bit_t   *SIGIN_BOARD0_BITIN4_BIT;
    hal_bit_t   *SIGIN_BOARD0_BITIN4_BIT_not;
    hal_bit_t   *SIGIN_BOARD0_BITIN5_BIT;
    hal_bit_t   *SIGIN_BOARD0_BITIN5_BIT_not;
    // raw variables
    int32_t VAROUT32_STEPDIR0_VELOCITY;
    int32_t VARIN32_STEPDIR0_POSITION;
    int32_t VAROUT32_STEPDIR1_VELOCITY;
    int32_t VARIN32_STEPDIR1_POSITION;
    int32_t VAROUT32_STEPDIR2_VELOCITY;
    int32_t VARIN32_STEPDIR2_POSITION;
    bool VAROUT1_STEPDIR0_ENABLE;
    bool VAROUT1_STEPDIR1_ENABLE;
    bool VARIN1_BITIN0_BIT;
    bool VAROUT1_STEPDIR2_ENABLE;
    bool VAROUT1_BITOUT0_BIT;
    bool VAROUT1_BITOUT1_BIT;
    bool VARIN1_BITIN1_BIT;
    bool VARIN1_BITIN2_BIT;
    bool VARIN1_BITIN3_BIT;
    bool VARIN1_BITIN4_BIT;
    bool VARIN1_BITIN5_BIT;

} data_t;
static data_t *data;

void register_signals(void) {
    int retval = 0;
    data->VAROUT32_STEPDIR0_VELOCITY = 0;
    data->VARIN32_STEPDIR0_POSITION = 0;
    data->VAROUT32_STEPDIR1_VELOCITY = 0;
    data->VARIN32_STEPDIR1_POSITION = 0;
    data->VAROUT32_STEPDIR2_VELOCITY = 0;
    data->VARIN32_STEPDIR2_POSITION = 0;
    data->VAROUT1_STEPDIR0_ENABLE = 0;
    data->VAROUT1_STEPDIR1_ENABLE = 0;
    data->VARIN1_BITIN0_BIT = 0;
    data->VAROUT1_STEPDIR2_ENABLE = 0;
    data->VAROUT1_BITOUT0_BIT = 0;
    data->VAROUT1_BITOUT1_BIT = 0;
    data->VARIN1_BITIN1_BIT = 0;
    data->VARIN1_BITIN2_BIT = 0;
    data->VARIN1_BITIN3_BIT = 0;
    data->VARIN1_BITIN4_BIT = 0;
    data->VARIN1_BITIN5_BIT = 0;

    if (retval = hal_pin_bit_newf(HAL_OUT, &(data->sys_status), comp_id, "board0.sys-status") != 0) error_handler(retval);
    if (retval = hal_pin_bit_newf(HAL_IN, &(data->sys_enable), comp_id, "board0.sys-enable") != 0) error_handler(retval);
    if (retval = hal_pin_bit_newf(HAL_IN, &(data->sys_enable_request), comp_id, "board0.sys-enable-request") != 0) error_handler(retval);
    if (retval = hal_pin_bit_newf(HAL_IN, &(data->machine_on), comp_id, "board0.machine-on") != 0) error_handler(retval);
    if (retval = hal_pin_bit_newf(HAL_IN, &(data->sys_simulation), comp_id, "board0.sys-simulation") != 0) error_handler(retval);
    if (retval = hal_pin_float_newf(HAL_OUT, &(data->duration), comp_id, "board0.duration") != 0) error_handler(retval);
    *data->duration = rtapi_get_time();
    if (retval = hal_pin_float_newf(HAL_IN, &(data->SIGOUT_BOARD0_STEPDIR0_VELOCITY_SCALE), comp_id, "board0.stepdir0.velocity-scale") != 0) error_handler(retval);
    *data->SIGOUT_BOARD0_STEPDIR0_VELOCITY_SCALE = 1.0;
    if (retval = hal_pin_float_newf(HAL_IN, &(data->SIGOUT_BOARD0_STEPDIR0_VELOCITY_OFFSET), comp_id, "board0.stepdir0.velocity-offset") != 0) error_handler(retval);
    *data->SIGOUT_BOARD0_STEPDIR0_VELOCITY_OFFSET = 0.0;
    if (retval = hal_pin_float_newf(HAL_IN, &(data->SIGOUT_BOARD0_STEPDIR0_VELOCITY), comp_id, "board0.stepdir0.velocity") != 0) error_handler(retval);
    *data->SIGOUT_BOARD0_STEPDIR0_VELOCITY = 0;
    if (retval = hal_pin_float_newf(HAL_IN, &(data->SIGIN_BOARD0_STEPDIR0_POSITION_SCALE), comp_id, "board0.stepdir0.position-scale") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR0_POSITION_SCALE = 1.0;
    if (retval = hal_pin_float_newf(HAL_IN, &(data->SIGIN_BOARD0_STEPDIR0_POSITION_OFFSET), comp_id, "board0.stepdir0.position-offset") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR0_POSITION_OFFSET = 0.0;
    if (retval = hal_pin_float_newf(HAL_OUT, &(data->SIGIN_BOARD0_STEPDIR0_POSITION), comp_id, "board0.stepdir0.position") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR0_POSITION = 0;
    if (retval = hal_pin_float_newf(HAL_OUT, &(data->SIGIN_BOARD0_STEPDIR0_POSITION_ABS), comp_id, "board0.stepdir0.position-abs") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR0_POSITION_ABS = 0;
    if (retval = hal_pin_s32_newf(HAL_OUT, &(data->SIGIN_BOARD0_STEPDIR0_POSITION_S32), comp_id, "board0.stepdir0.position-s32") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR0_POSITION_S32 = 0;
    if (retval = hal_pin_u32_newf(HAL_OUT, &(data->SIGIN_BOARD0_STEPDIR0_POSITION_U32_ABS), comp_id, "board0.stepdir0.position-u32-abs") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR0_POSITION_U32_ABS = 0;
    if (retval = hal_pin_bit_newf(HAL_IN, &(data->SIGOUT_BOARD0_STEPDIR0_ENABLE), comp_id, "board0.stepdir0.enable") != 0) error_handler(retval);
    *data->SIGOUT_BOARD0_STEPDIR0_ENABLE = 0;
    if (retval = hal_pin_float_newf(HAL_IN, &(data->SIGOUT_BOARD0_STEPDIR1_VELOCITY_SCALE), comp_id, "board0.stepdir1.velocity-scale") != 0) error_handler(retval);
    *data->SIGOUT_BOARD0_STEPDIR1_VELOCITY_SCALE = 1.0;
    if (retval = hal_pin_float_newf(HAL_IN, &(data->SIGOUT_BOARD0_STEPDIR1_VELOCITY_OFFSET), comp_id, "board0.stepdir1.velocity-offset") != 0) error_handler(retval);
    *data->SIGOUT_BOARD0_STEPDIR1_VELOCITY_OFFSET = 0.0;
    if (retval = hal_pin_float_newf(HAL_IN, &(data->SIGOUT_BOARD0_STEPDIR1_VELOCITY), comp_id, "board0.stepdir1.velocity") != 0) error_handler(retval);
    *data->SIGOUT_BOARD0_STEPDIR1_VELOCITY = 0;
    if (retval = hal_pin_float_newf(HAL_IN, &(data->SIGIN_BOARD0_STEPDIR1_POSITION_SCALE), comp_id, "board0.stepdir1.position-scale") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR1_POSITION_SCALE = 1.0;
    if (retval = hal_pin_float_newf(HAL_IN, &(data->SIGIN_BOARD0_STEPDIR1_POSITION_OFFSET), comp_id, "board0.stepdir1.position-offset") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR1_POSITION_OFFSET = 0.0;
    if (retval = hal_pin_float_newf(HAL_OUT, &(data->SIGIN_BOARD0_STEPDIR1_POSITION), comp_id, "board0.stepdir1.position") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR1_POSITION = 0;
    if (retval = hal_pin_float_newf(HAL_OUT, &(data->SIGIN_BOARD0_STEPDIR1_POSITION_ABS), comp_id, "board0.stepdir1.position-abs") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR1_POSITION_ABS = 0;
    if (retval = hal_pin_s32_newf(HAL_OUT, &(data->SIGIN_BOARD0_STEPDIR1_POSITION_S32), comp_id, "board0.stepdir1.position-s32") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR1_POSITION_S32 = 0;
    if (retval = hal_pin_u32_newf(HAL_OUT, &(data->SIGIN_BOARD0_STEPDIR1_POSITION_U32_ABS), comp_id, "board0.stepdir1.position-u32-abs") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR1_POSITION_U32_ABS = 0;
    if (retval = hal_pin_bit_newf(HAL_IN, &(data->SIGOUT_BOARD0_STEPDIR1_ENABLE), comp_id, "board0.stepdir1.enable") != 0) error_handler(retval);
    *data->SIGOUT_BOARD0_STEPDIR1_ENABLE = 0;
    if (retval = hal_pin_bit_newf(HAL_OUT, &(data->SIGIN_BOARD0_BITIN0_BIT), comp_id, "board0.bitin0.bit") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_BITIN0_BIT = 0;
    if (retval = hal_pin_bit_newf(HAL_OUT, &(data->SIGIN_BOARD0_BITIN0_BIT_not), comp_id, "board0.bitin0.bit-not") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_BITIN0_BIT_not = 1 - *data->SIGIN_BOARD0_BITIN0_BIT;
    if (retval = hal_pin_float_newf(HAL_IN, &(data->SIGOUT_BOARD0_STEPDIR2_VELOCITY_SCALE), comp_id, "board0.stepdir2.velocity-scale") != 0) error_handler(retval);
    *data->SIGOUT_BOARD0_STEPDIR2_VELOCITY_SCALE = 1.0;
    if (retval = hal_pin_float_newf(HAL_IN, &(data->SIGOUT_BOARD0_STEPDIR2_VELOCITY_OFFSET), comp_id, "board0.stepdir2.velocity-offset") != 0) error_handler(retval);
    *data->SIGOUT_BOARD0_STEPDIR2_VELOCITY_OFFSET = 0.0;
    if (retval = hal_pin_float_newf(HAL_IN, &(data->SIGOUT_BOARD0_STEPDIR2_VELOCITY), comp_id, "board0.stepdir2.velocity") != 0) error_handler(retval);
    *data->SIGOUT_BOARD0_STEPDIR2_VELOCITY = 0;
    if (retval = hal_pin_float_newf(HAL_IN, &(data->SIGIN_BOARD0_STEPDIR2_POSITION_SCALE), comp_id, "board0.stepdir2.position-scale") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR2_POSITION_SCALE = 1.0;
    if (retval = hal_pin_float_newf(HAL_IN, &(data->SIGIN_BOARD0_STEPDIR2_POSITION_OFFSET), comp_id, "board0.stepdir2.position-offset") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR2_POSITION_OFFSET = 0.0;
    if (retval = hal_pin_float_newf(HAL_OUT, &(data->SIGIN_BOARD0_STEPDIR2_POSITION), comp_id, "board0.stepdir2.position") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR2_POSITION = 0;
    if (retval = hal_pin_float_newf(HAL_OUT, &(data->SIGIN_BOARD0_STEPDIR2_POSITION_ABS), comp_id, "board0.stepdir2.position-abs") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR2_POSITION_ABS = 0;
    if (retval = hal_pin_s32_newf(HAL_OUT, &(data->SIGIN_BOARD0_STEPDIR2_POSITION_S32), comp_id, "board0.stepdir2.position-s32") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR2_POSITION_S32 = 0;
    if (retval = hal_pin_u32_newf(HAL_OUT, &(data->SIGIN_BOARD0_STEPDIR2_POSITION_U32_ABS), comp_id, "board0.stepdir2.position-u32-abs") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_STEPDIR2_POSITION_U32_ABS = 0;
    if (retval = hal_pin_bit_newf(HAL_IN, &(data->SIGOUT_BOARD0_STEPDIR2_ENABLE), comp_id, "board0.stepdir2.enable") != 0) error_handler(retval);
    *data->SIGOUT_BOARD0_STEPDIR2_ENABLE = 0;
    if (retval = hal_pin_bit_newf(HAL_IN, &(data->SIGOUT_BOARD0_BITOUT0_BIT), comp_id, "board0.bitout0.bit") != 0) error_handler(retval);
    *data->SIGOUT_BOARD0_BITOUT0_BIT = 0;
    if (retval = hal_pin_bit_newf(HAL_IN, &(data->SIGOUT_BOARD0_BITOUT1_BIT), comp_id, "board0.bitout1.bit") != 0) error_handler(retval);
    *data->SIGOUT_BOARD0_BITOUT1_BIT = 0;
    if (retval = hal_pin_bit_newf(HAL_OUT, &(data->SIGIN_BOARD0_BITIN1_BIT), comp_id, "board0.bitin1.bit") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_BITIN1_BIT = 0;
    if (retval = hal_pin_bit_newf(HAL_OUT, &(data->SIGIN_BOARD0_BITIN1_BIT_not), comp_id, "board0.bitin1.bit-not") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_BITIN1_BIT_not = 1 - *data->SIGIN_BOARD0_BITIN1_BIT;
    if (retval = hal_pin_bit_newf(HAL_OUT, &(data->SIGIN_BOARD0_BITIN2_BIT), comp_id, "board0.bitin2.bit") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_BITIN2_BIT = 0;
    if (retval = hal_pin_bit_newf(HAL_OUT, &(data->SIGIN_BOARD0_BITIN2_BIT_not), comp_id, "board0.bitin2.bit-not") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_BITIN2_BIT_not = 1 - *data->SIGIN_BOARD0_BITIN2_BIT;
    if (retval = hal_pin_bit_newf(HAL_OUT, &(data->SIGIN_BOARD0_BITIN3_BIT), comp_id, "board0.bitin3.bit") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_BITIN3_BIT = 0;
    if (retval = hal_pin_bit_newf(HAL_OUT, &(data->SIGIN_BOARD0_BITIN3_BIT_not), comp_id, "board0.bitin3.bit-not") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_BITIN3_BIT_not = 1 - *data->SIGIN_BOARD0_BITIN3_BIT;
    if (retval = hal_pin_bit_newf(HAL_OUT, &(data->SIGIN_BOARD0_BITIN4_BIT), comp_id, "board0.bitin4.bit") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_BITIN4_BIT = 0;
    if (retval = hal_pin_bit_newf(HAL_OUT, &(data->SIGIN_BOARD0_BITIN4_BIT_not), comp_id, "board0.bitin4.bit-not") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_BITIN4_BIT_not = 1 - *data->SIGIN_BOARD0_BITIN4_BIT;
    if (retval = hal_pin_bit_newf(HAL_OUT, &(data->SIGIN_BOARD0_BITIN5_BIT), comp_id, "board0.bitin5.bit") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_BITIN5_BIT = 0;
    if (retval = hal_pin_bit_newf(HAL_OUT, &(data->SIGIN_BOARD0_BITIN5_BIT_not), comp_id, "board0.bitin5.bit-not") != 0) error_handler(retval);
    *data->SIGIN_BOARD0_BITIN5_BIT_not = 1 - *data->SIGIN_BOARD0_BITIN5_BIT;
}

/*
    interface: UDP
*/

#include <string.h>
#include <stdio.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>

#define SEND_TIMEOUT_US 10
#define RECV_TIMEOUT_US 10
#define READ_PCK_DELAY_NS 1000
#define READ_PCK_TIMEOUT_MS 2

static int udpSocket;
static int errCount;
struct sockaddr_in dstAddr, srcAddr;
struct hostent *server;

int udp_init(const char *dstAddress, int dstPort, int srcPort) {
    int ret;

    // Create a UDP socket
    udpSocket = socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP);
    if (udpSocket < 0) {
        rtapi_print("ERROR: can't open socket: %s\n", strerror(errno));
        return -errno;
    }

    bzero((char*) &dstAddr, sizeof(dstAddr));
    dstAddr.sin_family = AF_INET;
    dstAddr.sin_addr.s_addr = inet_addr(dstAddress);
    dstAddr.sin_port = htons(dstPort);

    bzero((char*) &srcAddr, sizeof(srcAddr));
    srcAddr.sin_family = AF_INET;
    srcAddr.sin_addr.s_addr = htonl(INADDR_ANY);
    srcAddr.sin_port = htons(srcPort);

    rtapi_print("INFO: target is udp port: %s:%i\n", dstAddress, dstPort);
    rtapi_print("INFO: listening on udp port: %s:%i\n", "0.0.0.0", srcPort);

    // bind the local socket to SCR_PORT
    ret = bind(udpSocket, (struct sockaddr *) &srcAddr, sizeof(srcAddr));
    if (ret < 0) {
        rtapi_print("ERROR: can't bind: %s\n", strerror(errno));
        return -errno;
    }

    // Connect to send and receive only to the server_addr
    ret = connect(udpSocket, (struct sockaddr*) &dstAddr, sizeof(struct sockaddr_in));
    if (ret < 0) {
        rtapi_print("ERROR: can't connect: %s\n", strerror(errno));
        return -errno;
    }

    struct timeval timeout;
    timeout.tv_sec = 0;
    timeout.tv_usec = RECV_TIMEOUT_US;

    ret = setsockopt(udpSocket, SOL_SOCKET, SO_RCVTIMEO, (char*) &timeout, sizeof(timeout));
    if (ret < 0) {
        rtapi_print("ERROR: can't set receive timeout socket option: %s\n", strerror(errno));
        return -errno;
    }

    timeout.tv_usec = SEND_TIMEOUT_US;
    ret = setsockopt(udpSocket, SOL_SOCKET, SO_SNDTIMEO, (char*) &timeout,
                     sizeof(timeout));
    if (ret < 0) {
        rtapi_print("ERROR: can't set send timeout socket option: %s\n", strerror(errno));
        return -errno;
    }

    return 0;
}

void udp_tx(uint8_t *txBuffer, uint16_t size) {
    // Send datagram
    send(udpSocket, txBuffer, size, 0);
}

int udp_rx(uint8_t *rxBuffer, uint16_t size, uint8_t udp_async) {
    int i;
    int ret;
    long t1;
    long t2;
    uint8_t rxBufferTmp[1024];

    for (i = 0; i < 1024; i++) {
        rxBufferTmp[i] = 0;
    }

    // Receive incoming datagram
    if (udp_async == 1) {
        ret = recv(udpSocket, rxBufferTmp, size * 2, MSG_DONTWAIT);
    } else {
        t1 = rtapi_get_time();
        do {
            ret = recv(udpSocket, rxBufferTmp, size * 2, 0);
            if (ret < 0) {
                rtapi_delay(READ_PCK_DELAY_NS);
            }
            t2 = rtapi_get_time();
        }
        while ((ret < 0) && ((t2 - t1) < READ_PCK_TIMEOUT_MS * 1000 * 1000));
    }

    if (ret > 0) {
        errCount = 0;
        if (ret == size) {
            memcpy(rxBuffer, rxBufferTmp, size);
        } else {
            rtapi_print("wrong size = %d\n", ret);
            for (i = 0; i < ret; i++) {
                rtapi_print("%d ", rxBufferTmp[i]);
            }
            rtapi_print("\n");
        }
        /*
        printf("rx:");
        for (i = 0; i < ret; i++) {
            printf(" %d,", rxBuffer[i]);
        }
        printf("\n");
        */
    } else {
        errCount++;
        // rtapi_print("Ethernet TIMEOUT: N = %d (ret: %d)\n", errCount, ret);
    }

    return ret;
}

void udp_exit(void) {
}

int interface_init(void) {
    udp_init(UDP_IP, DST_PORT, SRC_PORT);
    return 0;
}

void interface_exit(void) {
    udp_exit();
}


/*
    hal functions
*/

/***********************************************************************
*                       HELPER FUNCTIONS                               *
************************************************************************/

uint16_t crc16_update(uint16_t crc, uint8_t a) {
	int i;

	crc ^= (uint16_t)a;
	for (i = 0; i < 8; ++i) {
		if (crc & 1)
			crc = (crc >> 1) ^ 0xA001;
		else
			crc = (crc >> 1);
	}

	return crc;
}

int error_handler(int retval) {
    if (retval < 0) {
        rtapi_print_msg(RTAPI_MSG_ERR, "%s: ERROR: pin export failed with err=%i\n", modname, retval);
        hal_exit(comp_id);
        return -1;
    }
}

int rtapi_app_main(void) {
    char name[HAL_NAME_LEN + 1];
    int retval = 0;
    int n = 0;
    data = hal_malloc(sizeof(data_t));
    comp_id = hal_init(modname);
    if (comp_id < 0) {
        rtapi_print_msg(RTAPI_MSG_ERR, "%s ERROR: hal_init() failed \n", modname);
        return -1;
    }
    register_signals();
    rtapi_snprintf(name, sizeof(name), "%s.update-freq", prefix);
    rtapi_snprintf(name, sizeof(name), "%s.readwrite", prefix);
    retval = hal_export_funct(name, rio_readwrite, data, 1, 0, comp_id);
    if (retval < 0) {
        rtapi_print_msg(RTAPI_MSG_ERR, "%s: ERROR: read function export failed\n", modname);
        hal_exit(comp_id);
        return -1;
    }
    rtapi_print_msg(RTAPI_MSG_INFO, "%s: installed driver\n", modname);
    hal_ready(comp_id);

    interface_init();

    rio_readwrite(NULL, 0);

    return 0;
}

void rtapi_app_exit(void) {
    interface_exit();
    hal_exit(comp_id);
}

/***********************************************************************/


/***********************************************************************
*                         PLUGIN GLOBALS                               *
************************************************************************/
















/***********************************************************************/

// Generated by component_signal_converter()
// output: SIGOUT -> calc -> VAROUT -> txBuffer
void convert_varout32_stepdir0_velocity(data_t *data){
    float value = *data->SIGOUT_BOARD0_STEPDIR0_VELOCITY;
    value = value * *data->SIGOUT_BOARD0_STEPDIR0_VELOCITY_SCALE;
    value = value + *data->SIGOUT_BOARD0_STEPDIR0_VELOCITY_OFFSET;
    if (value != 0) {
                value = OSC_CLOCK / value / 2;
            }
    data->VAROUT32_STEPDIR0_VELOCITY = value;
}

void convert_varout1_stepdir0_enable(data_t *data){
    bool value = *data->SIGOUT_BOARD0_STEPDIR0_ENABLE;
    
    data->VAROUT1_STEPDIR0_ENABLE = value;
}

void convert_varout32_stepdir1_velocity(data_t *data){
    float value = *data->SIGOUT_BOARD0_STEPDIR1_VELOCITY;
    value = value * *data->SIGOUT_BOARD0_STEPDIR1_VELOCITY_SCALE;
    value = value + *data->SIGOUT_BOARD0_STEPDIR1_VELOCITY_OFFSET;
    if (value != 0) {
                value = OSC_CLOCK / value / 2;
            }
    data->VAROUT32_STEPDIR1_VELOCITY = value;
}

void convert_varout1_stepdir1_enable(data_t *data){
    bool value = *data->SIGOUT_BOARD0_STEPDIR1_ENABLE;
    
    data->VAROUT1_STEPDIR1_ENABLE = value;
}

void convert_varout32_stepdir2_velocity(data_t *data){
    float value = *data->SIGOUT_BOARD0_STEPDIR2_VELOCITY;
    value = value * *data->SIGOUT_BOARD0_STEPDIR2_VELOCITY_SCALE;
    value = value + *data->SIGOUT_BOARD0_STEPDIR2_VELOCITY_OFFSET;
    if (value != 0) {
                value = OSC_CLOCK / value / 2;
            }
    data->VAROUT32_STEPDIR2_VELOCITY = value;
}

void convert_varout1_stepdir2_enable(data_t *data){
    bool value = *data->SIGOUT_BOARD0_STEPDIR2_ENABLE;
    
    data->VAROUT1_STEPDIR2_ENABLE = value;
}

void convert_varout1_bitout0_bit(data_t *data){
    bool value = *data->SIGOUT_BOARD0_BITOUT0_BIT;
    
    data->VAROUT1_BITOUT0_BIT = value;
}

void convert_varout1_bitout1_bit(data_t *data){
    bool value = *data->SIGOUT_BOARD0_BITOUT1_BIT;
    
    data->VAROUT1_BITOUT1_BIT = value;
}


// input: rxBuffer -> VAROUT -> calc -> SIGOUT
void convert_sigin_board0_stepdir0_position(data_t *data) {
    float value = data->VARIN32_STEPDIR0_POSITION;
    float offset = *data->SIGIN_BOARD0_STEPDIR0_POSITION_OFFSET;
    float scale = *data->SIGIN_BOARD0_STEPDIR0_POSITION_SCALE;
    float last_value = *data->SIGIN_BOARD0_STEPDIR0_POSITION;
    static float last_raw_value = 0.0;
    float raw_value = value;
    value = value + offset;
    value = value / scale;
    if (*data->sys_simulation == 1) {
        value = *data->SIGIN_BOARD0_STEPDIR0_POSITION + *data->SIGOUT_BOARD0_STEPDIR0_VELOCITY / 1000.0;
    }
    *data->SIGIN_BOARD0_STEPDIR0_POSITION_ABS = abs(value);
    *data->SIGIN_BOARD0_STEPDIR0_POSITION_S32 = value;
    *data->SIGIN_BOARD0_STEPDIR0_POSITION_U32_ABS = abs(value);
    *data->SIGIN_BOARD0_STEPDIR0_POSITION = value;

    last_raw_value = raw_value;
}

void convert_sigin_board0_stepdir1_position(data_t *data) {
    float value = data->VARIN32_STEPDIR1_POSITION;
    float offset = *data->SIGIN_BOARD0_STEPDIR1_POSITION_OFFSET;
    float scale = *data->SIGIN_BOARD0_STEPDIR1_POSITION_SCALE;
    float last_value = *data->SIGIN_BOARD0_STEPDIR1_POSITION;
    static float last_raw_value = 0.0;
    float raw_value = value;
    value = value + offset;
    value = value / scale;
    if (*data->sys_simulation == 1) {
        value = *data->SIGIN_BOARD0_STEPDIR1_POSITION + *data->SIGOUT_BOARD0_STEPDIR1_VELOCITY / 1000.0;
    }
    *data->SIGIN_BOARD0_STEPDIR1_POSITION_ABS = abs(value);
    *data->SIGIN_BOARD0_STEPDIR1_POSITION_S32 = value;
    *data->SIGIN_BOARD0_STEPDIR1_POSITION_U32_ABS = abs(value);
    *data->SIGIN_BOARD0_STEPDIR1_POSITION = value;

    last_raw_value = raw_value;
}

void convert_sigin_board0_bitin0_bit(data_t *data) {
    bool value = data->VARIN1_BITIN0_BIT;
    *data->SIGIN_BOARD0_BITIN0_BIT = value;
    *data->SIGIN_BOARD0_BITIN0_BIT_not = 1 - value;
}

void convert_sigin_board0_stepdir2_position(data_t *data) {
    float value = data->VARIN32_STEPDIR2_POSITION;
    float offset = *data->SIGIN_BOARD0_STEPDIR2_POSITION_OFFSET;
    float scale = *data->SIGIN_BOARD0_STEPDIR2_POSITION_SCALE;
    float last_value = *data->SIGIN_BOARD0_STEPDIR2_POSITION;
    static float last_raw_value = 0.0;
    float raw_value = value;
    value = value + offset;
    value = value / scale;
    if (*data->sys_simulation == 1) {
        value = *data->SIGIN_BOARD0_STEPDIR2_POSITION + *data->SIGOUT_BOARD0_STEPDIR2_VELOCITY / 1000.0;
    }
    *data->SIGIN_BOARD0_STEPDIR2_POSITION_ABS = abs(value);
    *data->SIGIN_BOARD0_STEPDIR2_POSITION_S32 = value;
    *data->SIGIN_BOARD0_STEPDIR2_POSITION_U32_ABS = abs(value);
    *data->SIGIN_BOARD0_STEPDIR2_POSITION = value;

    last_raw_value = raw_value;
}

void convert_sigin_board0_bitin1_bit(data_t *data) {
    bool value = data->VARIN1_BITIN1_BIT;
    *data->SIGIN_BOARD0_BITIN1_BIT = value;
    *data->SIGIN_BOARD0_BITIN1_BIT_not = 1 - value;
}

void convert_sigin_board0_bitin2_bit(data_t *data) {
    bool value = data->VARIN1_BITIN2_BIT;
    *data->SIGIN_BOARD0_BITIN2_BIT = value;
    *data->SIGIN_BOARD0_BITIN2_BIT_not = 1 - value;
}

void convert_sigin_board0_bitin3_bit(data_t *data) {
    bool value = data->VARIN1_BITIN3_BIT;
    *data->SIGIN_BOARD0_BITIN3_BIT = value;
    *data->SIGIN_BOARD0_BITIN3_BIT_not = 1 - value;
}

void convert_sigin_board0_bitin4_bit(data_t *data) {
    bool value = data->VARIN1_BITIN4_BIT;
    *data->SIGIN_BOARD0_BITIN4_BIT = value;
    *data->SIGIN_BOARD0_BITIN4_BIT_not = 1 - value;
}

void convert_sigin_board0_bitin5_bit(data_t *data) {
    bool value = data->VARIN1_BITIN5_BIT;
    *data->SIGIN_BOARD0_BITIN5_BIT = value;
    *data->SIGIN_BOARD0_BITIN5_BIT_not = 1 - value;
}



// Generated by component_buffer_converter()
void convert_outputs(void) {
    // output loop: SIGOUT -> calc -> VAROUT -> txBuffer
    convert_varout32_stepdir0_velocity(data);
    convert_varout1_stepdir0_enable(data);
    convert_varout32_stepdir1_velocity(data);
    convert_varout1_stepdir1_enable(data);
    convert_varout32_stepdir2_velocity(data);
    convert_varout1_stepdir2_enable(data);
    convert_varout1_bitout0_bit(data);
    convert_varout1_bitout1_bit(data);
}

void convert_inputs(void) {
    // input: rxBuffer -> VAROUT -> calc -> SIGOUT
    convert_sigin_board0_stepdir0_position(data);
    convert_sigin_board0_stepdir1_position(data);
    convert_sigin_board0_bitin0_bit(data);
    convert_sigin_board0_stepdir2_position(data);
    convert_sigin_board0_bitin1_bit(data);
    convert_sigin_board0_bitin2_bit(data);
    convert_sigin_board0_bitin3_bit(data);
    convert_sigin_board0_bitin4_bit(data);
    convert_sigin_board0_bitin5_bit(data);
}

// Generated by component_buffer()
void write_txbuffer(uint8_t *txBuffer) {
    // PC -> FPGA (133 + 35)
    int i = 0;
    for (i = 0; i < BUFFER_SIZE; i++) {
        txBuffer[i] = 0;
    }
    // raw vars to txBuffer
    txBuffer[0] = 0x74; // 168
    txBuffer[1] = 0x69; // 160
    txBuffer[2] = 0x72; // 152
    txBuffer[3] = 0x77; // 144
    memcpy(&txBuffer[4], &data->VAROUT32_STEPDIR0_VELOCITY, 4); // 136
    memcpy(&txBuffer[8], &data->VAROUT32_STEPDIR1_VELOCITY, 4); // 104
    memcpy(&txBuffer[12], &data->VAROUT32_STEPDIR2_VELOCITY, 4); // 72
    txBuffer[16] |= (data->VAROUT1_STEPDIR0_ENABLE<<7); // 40
    txBuffer[16] |= (data->VAROUT1_STEPDIR1_ENABLE<<6); // 39
    txBuffer[16] |= (data->VAROUT1_STEPDIR2_ENABLE<<5); // 38
    txBuffer[16] |= (data->VAROUT1_BITOUT0_BIT<<4); // 37
    txBuffer[16] |= (data->VAROUT1_BITOUT1_BIT<<3); // 36
    // FILL: 35
}

void read_rxbuffer(uint8_t *rxBuffer) {
    // FPGA -> PC (166 + 2)
    // memcpy(&header, &rxBuffer[0], 4) // 168;
    memcpy(&fpga_timestamp, &rxBuffer[4], 4); // 136
    memcpy(&data->VARIN32_STEPDIR0_POSITION, &rxBuffer[8], 4); // 104
    memcpy(&data->VARIN32_STEPDIR1_POSITION, &rxBuffer[12], 4); // 72
    memcpy(&data->VARIN32_STEPDIR2_POSITION, &rxBuffer[16], 4); // 40
    data->VARIN1_BITIN0_BIT = (rxBuffer[20] & (1<<7)); // 8
    data->VARIN1_BITIN1_BIT = (rxBuffer[20] & (1<<6)); // 7
    data->VARIN1_BITIN2_BIT = (rxBuffer[20] & (1<<5)); // 6
    data->VARIN1_BITIN3_BIT = (rxBuffer[20] & (1<<4)); // 5
    data->VARIN1_BITIN4_BIT = (rxBuffer[20] & (1<<3)); // 4
    data->VARIN1_BITIN5_BIT = (rxBuffer[20] & (1<<2)); // 3
    // FILL: 2
}

void rio_readwrite(void *inst, long period) {
    int ret = 0;
    uint8_t i = 0;
    uint8_t rxBuffer[BUFFER_SIZE * 2];
    uint8_t txBuffer[BUFFER_SIZE * 2];
    if (*data->sys_enable_request == 1) {
        *data->sys_status = 1;
    }
    long stamp_new = rtapi_get_time();
    float duration2 = (stamp_new - stamp_last) / 1000.0;
    stamp_last = stamp_new;
    float timestamp = (float)fpga_timestamp / (float)OSC_CLOCK;
    *data->duration = timestamp - fpga_stamp_last;
    fpga_stamp_last = timestamp;
    if (*data->sys_enable == 1 && *data->sys_status == 1) {
        pkg_counter += 1;
        convert_outputs();
        if (*data->sys_simulation != 1) {
            write_txbuffer(txBuffer);
#ifdef UDP_ASYNC
            ret = udp_rx(rxBuffer, BUFFER_SIZE, 1);
            udp_tx(txBuffer, BUFFER_SIZE);
#else
            udp_tx(txBuffer, BUFFER_SIZE);
            ret = udp_rx(rxBuffer, BUFFER_SIZE, 0);
#endif
            if (ret == BUFFER_SIZE && rxBuffer[0] == 97 && rxBuffer[1] == 116 && rxBuffer[2] == 97 && rxBuffer[3] == 100) {
                if (err_counter > 0) {
                    err_counter = 0;
                    rtapi_print("recovered..\n");
                }
                read_rxbuffer(rxBuffer);
                convert_inputs();
            } else {
                err_counter += 1;
                err_total += 1;
                if (ret != BUFFER_SIZE) {
                    rtapi_print("%i: wrong data size (len %i/%i err %i/3) - (%i %i - %0.4f %%)", stamp_new, ret, BUFFER_SIZE, err_counter, err_total, pkg_counter, (float)err_total * 100.0 / (float)pkg_counter);
                } else {
                    rtapi_print("%i: wrong header (%i/3) - (%i %i - %0.4f %%):", stamp_new, err_counter, err_total, pkg_counter, (float)err_total * 100.0 / (float)pkg_counter);
                }
                for (i = 0; i < ret; i++) {
                    rtapi_print("%d ",rxBuffer[i]);
                }
                rtapi_print("\n");
                if (err_counter > 3) {
                    rtapi_print("too many errors..\n");
                    *data->sys_status = 0;
                }
            }
        } else {
            convert_inputs();
        }
    } else {
        *data->sys_status = 0;
    }
}

